openapi: 3.0.0
info:
  title: Stripe Events API
paths:
  /v1/events:
    get:
      description: >-
        <p>List events, going back up to 30 days. Each event data is rendered
        according to Stripe API version at its creation time, specified in <a
        href="/docs/api/events/object">event object</a> <code>api_version</code>
        attribute (not according to your current Stripe API version or
        <code>Stripe-Version</code> header).</p>
      summary: Retrieve Events
      tags:
        - Events
  /v1/events/{id}:
    get:
      description: >-
        <p>Retrieves the details of an event. Supply the unique identifier of
        the event, which you might have received in a webhook.</p>
      summary: Retrieve Event
      tags:
        - Events
tags:
  - name: Events
    description: Needs a description.
