swagger: '2.0'
info:
  title: Hotel Name Autocomplete
host: test.api.amadeus.com
basePath: /v1
schemes:
  - https
consumes:
  - application/vnd.amadeus+json
produces:
  - application/vnd.amadeus+json
paths:
  /reference-data/locations/hotel:
    get:
      tags:
        - Returns
        - List
        - Of
        - Hotels
        - Matching
        - Given
        - Keyword.
        - Reference
        - Data
        - Locations
        - Hotel
      summary: Returns a list of hotels matching a given keyword.
      description: null
