openapi: 3.0.0
info:
  title: Trip Parser
x-release-note:
  '3.0':
    - First release of Trip Parser V3
paths:
  /travel/trip-parser:
    post:
      tags:
        - Trip
        - Parser
        - Request
        - Travel
        - Trip
        - Parser
      summary: POST Trip Parser request
      description: null
