openapi: 3.1.0
info:
  title: AWSMigrationHub
  description: >-
    <p>The AWS Migration Hub API methods help to obtain server and application
    migration status and integrate your resource-specific migration tool by
    providing a programmatic interface to Migration Hub.</p> <p>Remember that
    you must set your AWS Migration Hub home region before you call any of these
    APIs, or a <code>HomeRegionNotSetException</code> error will be returned.
    Also, you must make the API calls while in your home region.</p>
paths:
  /:
    POST:
      summary: PutResourceAttributes
      description: >-
        <p>Provides identifying details of the resource being migrated so that
        it can be associated in the Application Discovery Service repository.
        This association occurs asynchronously after
        <code>PutResourceAttributes</code> returns.</p> <important> <ul> <li>
        <p>Keep in mind that subsequent calls to PutResourceAttributes will
        override previously stored attributes. For example, if it is first
        called with a MAC address, but later, it is desired to <i>add</i> an IP
        address, it will then be required to call it with <i>both</i> the IP and
        MAC addresses to prevent overriding the MAC address.</p> </li> <li>
        <p>Note the instructions regarding the special use case of the <a
        href="https://docs.aws.amazon.com/migrationhub/latest/ug/API_PutResourceAttributes.html#migrationhub-PutResourceAttributes-request-ResourceAttributeList">
        <code>ResourceAttributeList</code> </a> parameter when specifying any
        "VM" related value.</p> </li> </ul> </important> <note> <p>Because this
        is an asynchronous call, it will always return 200, whether an
        association occurs or not. To confirm if an association was found based
        on the provided details, call <code>ListDiscoveredResources</code>.</p>
        </note>
tags: []
