openapi: 3.1.0
info:
  title: cloudcontrol
  description: >-
    <p>For more information about Amazon Web Services Cloud Control API, see the
    <a
    href="https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/what-is-cloudcontrolapi.html">Amazon
    Web Services Cloud Control API User Guide</a>.</p>
paths:
  /:
    POST:
      summary: UpdateResource
      description: >-
        <p>Updates the specified property values in the resource.</p> <p>You
        specify your resource property updates as a list of patch operations
        contained in a JSON patch document that adheres to the <a
        href="https://datatracker.ietf.org/doc/html/rfc6902"> <i>RFC 6902 -
        JavaScript Object Notation (JSON) Patch</i> </a> standard.</p> <p>For
        details on how Cloud Control API performs resource update operations,
        see <a
        href="https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/resource-operations-update.html">Updating
        a resource</a> in the <i>Amazon Web Services Cloud Control API User
        Guide</i>.</p> <p>After you have initiated a resource update request,
        you can monitor the progress of your request by calling <a
        href="https://docs.aws.amazon.com/cloudcontrolapi/latest/APIReference/API_GetResourceRequestStatus.html">GetResourceRequestStatus</a>
        using the <code>RequestToken</code> of the <code>ProgressEvent</code>
        returned by <code>UpdateResource</code>.</p> <p>For more information
        about the properties of a specific resource, refer to the related topic
        for the resource in the <a
        href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html">Resource
        and property types reference</a> in the <i>CloudFormation Users
        Guide</i>.</p>
tags: []
