openapi: 3.1.0
info:
  title: connectparticipant
  description: >-
    <p>Amazon Connect is an easy-to-use omnichannel cloud contact center service
    that enables companies of any size to deliver superior customer service at a
    lower cost. Amazon Connect communications capabilities make it easy for
    companies to deliver personalized interactions across communication
    channels, including chat. </p> <p>Use the Amazon Connect Participant Service
    to manage participants (for example, agents, customers, and managers
    listening in), and to send messages and events within a chat contact. The
    APIs in the service enable the following: sending chat messages, attachment
    sharing, managing a participant's connection state and message events, and
    retrieving chat transcripts.</p>
paths:
  /participant/complete-attachment-upload:
    POST:
      summary: CompleteAttachmentUpload
      description: >-
        <p>Allows you to confirm that the attachment has been uploaded using the
        pre-signed URL provided in StartAttachmentUpload API. </p> <note> <p>
        <code>ConnectionToken</code> is used for invoking this API instead of
        <code>ParticipantToken</code>.</p> </note> <p>The Amazon Connect
        Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/connection:
    POST:
      summary: CreateParticipantConnection
      description: >-
        <p>Creates the participant's connection. </p> <note> <p>
        <code>ParticipantToken</code> is used for invoking this API instead of
        <code>ConnectionToken</code>.</p> </note> <p>The participant token is
        valid for the lifetime of the participant â€“ until they are part of a
        contact.</p> <p>The response URL for <code>WEBSOCKET</code> Type has a
        connect expiry timeout of 100s. Clients must manually connect to the
        returned websocket URL and subscribe to the desired topic. </p> <p>For
        chat, you need to publish the following on the established websocket
        connection:</p> <p>
        <code>{"topic":"aws/subscribe","content":{"topics":["aws/chat"]}}</code>
        </p> <p>Upon websocket URL expiry, as specified in the response
        ConnectionExpiry parameter, clients need to call this API again to
        obtain a new websocket URL and perform the same steps as before.</p> <p>
        <b>Message streaming support</b>: This API can also be used together
        with the <a
        href="https://docs.aws.amazon.com/connect/latest/APIReference/API_StartContactStreaming.html">StartContactStreaming</a>
        API to create a participant connection for chat contacts that are not
        using a websocket. For more information about message streaming, <a
        href="https://docs.aws.amazon.com/connect/latest/adminguide/chat-message-streaming.html">Enable
        real-time chat message streaming</a> in the <i>Amazon Connect
        Administrator Guide</i>.</p> <p> <b>Feature specifications</b>: For
        information about feature specifications, such as the allowed number of
        open websocket connections per participant, see <a
        href="https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-service-limits.html#feature-limits">Feature
        specifications</a> in the <i>Amazon Connect Administrator Guide</i>.
        </p> <note> <p>The Amazon Connect Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p> </note>
  /participant/views/{ViewToken}:
    GET:
      summary: DescribeView
      description: <p>Retrieves the view for the specified view token.</p>
  /participant/disconnect:
    POST:
      summary: DisconnectParticipant
      description: >-
        <p>Disconnects a participant. </p> <note> <p>
        <code>ConnectionToken</code> is used for invoking this API instead of
        <code>ParticipantToken</code>.</p> </note> <p>The Amazon Connect
        Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/attachment:
    POST:
      summary: GetAttachment
      description: >-
        <p>Provides a pre-signed URL for download of a completed attachment.
        This is an asynchronous API for use with active contacts.</p> <note> <p>
        <code>ConnectionToken</code> is used for invoking this API instead of
        <code>ParticipantToken</code>.</p> </note> <p>The Amazon Connect
        Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/transcript:
    POST:
      summary: GetTranscript
      description: >-
        <p>Retrieves a transcript of the session, including details about any
        attachments. For information about accessing past chat contact
        transcripts for a persistent chat, see <a
        href="https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html">Enable
        persistent chat</a>. </p> <note> <p> <code>ConnectionToken</code> is
        used for invoking this API instead of <code>ParticipantToken</code>.</p>
        </note> <p>The Amazon Connect Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/event:
    POST:
      summary: SendEvent
      description: >-
        <p>Sends an event. </p> <note> <p> <code>ConnectionToken</code> is used
        for invoking this API instead of <code>ParticipantToken</code>.</p>
        </note> <p>The Amazon Connect Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/message:
    POST:
      summary: SendMessage
      description: >-
        <p>Sends a message.</p> <note> <p> <code>ConnectionToken</code> is used
        for invoking this API instead of <code>ParticipantToken</code>.</p>
        </note> <p>The Amazon Connect Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
  /participant/start-attachment-upload:
    POST:
      summary: StartAttachmentUpload
      description: >-
        <p>Provides a pre-signed Amazon S3 URL in response for uploading the
        file directly to S3.</p> <note> <p> <code>ConnectionToken</code> is used
        for invoking this API instead of <code>ParticipantToken</code>.</p>
        </note> <p>The Amazon Connect Participant Service APIs do not use <a
        href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Signature
        Version 4 authentication</a>.</p>
tags: []
