openapi: 3.0.0
info:
  title: Stripe Balance API
paths:
  /v1/balance:
    get:
      description: >-
        <p>Retrieves the current account balance, based on the authentication
        that was used to make the request.
         For a sample request, see <a href="/docs/connect/account-balances#accounting-for-negative-balances">Accounting for negative balances</a>.</p>
  /v1/balance/history:
    get:
      description: >-
        <p>Returns a list of transactions that have contributed to the Stripe
        account balance (e.g., charges, transfers, and so forth). The
        transactions are returned in sorted order, with the most recent
        transactions appearing first.</p>


        <p>Note that this endpoint was previously called “Balance history” and
        used the path <code>/v1/balance/history</code>.</p>
  /v1/balance/history/{id}:
    get:
      description: >-
        <p>Retrieves the balance transaction with the given ID.</p>


        <p>Note that this endpoint previously used the path
        <code>/v1/balance/history/:id</code>.</p>
  /v1/balance_transactions:
    get:
      description: >-
        <p>Returns a list of transactions that have contributed to the Stripe
        account balance (e.g., charges, transfers, and so forth). The
        transactions are returned in sorted order, with the most recent
        transactions appearing first.</p>


        <p>Note that this endpoint was previously called “Balance history” and
        used the path <code>/v1/balance/history</code>.</p>
  /v1/balance_transactions/{id}:
    get:
      description: >-
        <p>Retrieves the balance transaction with the given ID.</p>


        <p>Note that this endpoint previously used the path
        <code>/v1/balance/history/:id</co
