openapi: 3.0.0
info:
  title: Stripe Checkout API
paths:
  /v1/checkout/sessions:
    get:
      description: <p>Returns a list of Checkout Sessions.</p>
    post:
      description: <p>Creates a Session object.</p>
  /v1/checkout/sessions/{session}:
    get:
      description: <p>Retrieves a Session object.</p>
  /v1/checkout/sessions/{session}/expire:
    post:
      description: >-
        <p>A Session can be expired when it is in one of these statuses:
        <code>open</code> </p>


        <p>After it expires, a customer canâ€™t complete a Session and customers
        loading the Session see a message saying the Session is expired.</p>
  /v1/checkout/sessions/{session}/line_items:
    get:
      description: >-
        <p>When retrieving a Checkout Session, there is an includable
        <strong>line_items</strong> property containing the first handful of
        those items. There is also a URL where you can retrieve the full
        (paginated) list of line it
