openapi: 3.0.0
info:
  title: Stripe Country API
paths:
  /v1/country_specs:
    get:
      description: <p>Lists all Country Spec objects available in the API.</p>
  /v1/country_specs/{country}:
    get:
      description: <p>Returns a Country Spec for a given Country c
