openapi: 3.0.0
info:
  title: Stripe Credit Notes API
paths:
  /v1/credit_notes:
    get:
      description: <p>Returns a list of credit notes.</p>
      tags:
        - V1
        - Credit_notes
    post:
      description: >-
        <p>Issue a credit note to adjust the amount of a finalized invoice. For
        a <code>status=open</code> invoice, a credit note reduces

        its <code>amount_due</code>. For a <code>status=paid</code> invoice, a
        credit note does not affect its <code>amount_due</code>. Instead, it can
        result

        in any combination of the following:</p>


        <ul>

        <li>Refund: create a new refund (using <code>refund_amount</code>) or
        link an existing refund (using <code>refund</code>).</li>

        <li>Customer balance credit: credit the customer’s balance (using
        <code>credit_amount</code>) which will be automatically applied to their
        next invoice when it’s finalized.</li>

        <li>Outside of Stripe credit: record the amount that is or will be
        credited outside of Stripe (using <code>out_of_band_amount</code>).</li>

        </ul>


        <p>For post-payment credit notes the sum of the refund, credit and
        outside of Stripe amounts must equal the credit note total.</p>


        <p>You may issue multiple credit notes for an invoice. Each credit note
        will increment the invoice’s
        <code>pre_payment_credit_notes_amount</code>

        or <code>post_payment_credit_notes_amount</code> depending on its
        <code>status</code> at the time of credit note creation.</p>
      tags:
        - V1
        - Credit_notes
  /v1/credit_notes/preview:
    get:
      description: <p>Get a preview of a credit note without creating it.</p>
      tags:
        - V1
        - Credit_notes
        - Preview
  /v1/credit_notes/preview/lines:
    get:
      description: >-
        <p>When retrieving a credit note preview, you’ll get a
        <strong>lines</strong> property containing the first handful of those
        items. This URL you can retrieve the full (paginated) list of line
        items.</p>
      tags:
        - V1
        - Credit_notes
        - Preview
        - Lines
  /v1/credit_notes/{credit_note}/lines:
    get:
      description: >-
        <p>When retrieving a credit note, you’ll get a <strong>lines</strong>
        property containing the the first handful of those items. There is also
        a URL where you can retrieve the full (paginated) list of line
        items.</p>
      tags:
        - V1
        - Credit_notes
        - Preview
        - Lines
        - Credit_note
  /v1/credit_notes/{id}:
    get:
      description: <p>Retrieves the credit note object with the given identifier.</p>
      tags:
        - V1
        - Credit_notes
        - Preview
        - Lines
        - Credit_note
        - Id
    post:
      description: <p>Updates an existing credit note.</p>
      tags:
        - V1
        - Credit_notes
        - Preview
        - Lines
        - Credit_note
        - Id
  /v1/credit_notes/{id}/void:
    post:
      description: >-
        <p>Marks a credit note as void. Learn more about <a
        href="/docs/billing/invoices/credit-notes#voiding">voiding credit note
      tags:
        - V1
        - Credit_notes
        - Preview
        - Lines
        - Credit_note
        - Id
        - Vo
