openapi: 3.0.0
info:
  title: Stripe Disputes API
paths:
  /v1/disputes:
    get:
      description: <p>Returns a list of your disputes.</p>
      summary: Retrieve Disputes
      tags:
        - Retrieve
        - Disputes
        - V1
        - Disputes
  /v1/disputes/{dispute}:
    get:
      description: <p>Retrieves the dispute with the given ID.</p>
      summary: Retrieve Dispute
      tags:
        - Retrieve
        - Dispute
        - V1
        - Disputes
        - Dispute
    post:
      description: >-
        <p>When you get a dispute, contacting your customer is always the best
        first step. If that doesnâ€™t work, you can submit evidence to help us
        resolve the dispute in your favor. You can do this in your <a
        href="https://dashboard.stripe.com/disputes">dashboard</a>, but if you
        prefer, you can use the API to submit evidence programmatically.</p>


        <p>Depending on your dispute type, different evidence fields will give
        you a better chance of winning your dispute. To figure out which
        evidence fields to provide, see our <a
        href="/docs/disputes/categories">guide to dispute types</a>.</p>
      summary: Update Dispute
      tags:
        - Update
        - Dispute
        - V1
        - Disputes
        - Dispute
  /v1/disputes/{dispute}/close:
    post:
      description: >-
        <p>Closing the dispute for a charge indicates that you do not have any
        evidence to submit and are essentially dismissing the dispute,
        acknowledging it as lost.</p>


        <p>The status of the dispute will change from
        <code>needs_response</code> to <code>lost</code>. <em>Closing a dispute
        is irreversible</em>.</p>
      summary: Close Dispute
      tags:
        - Close
        - Dispute
        - V1
        - Disputes
        - Dispute
        - Close
tags:
  - name: Disputes
    description: Needs a description.
  - name: Closed
    description: Needs a descriptio
