openapi: 3.0.0
info:
  title: Stripe Exchange Rates API
paths:
  /v1/exchange_rates:
    get:
      description: >-
        <p>Returns a list of objects that contain the rates at which foreign
        currencies are converted to one another. Only shows the currencies for
        which Stripe supports.</p>
  /v1/exchange_rates/{rate_id}:
    get:
      description: >-
        <p>Retrieves the exchange rates from the given currency to every
        supported curre
