openapi: 3.0.0
info:
  title: Stripe Files API
paths:
  /v1/files:
    get:
      description: >-
        <p>Returns a list of the files that your account has access to. Stripe
        sorts and returns the files by their creation dates, placing the most
        recently created files at the top.</p>
      tags:
        - V1
        - Files
    post:
      description: >-
        <p>To upload a file to Stripe, you need to send a request of type
        <code>multipart/form-data</code>. Include the file you want to upload in
        the request, and the parameters for creating a file.</p>


        <p>All of Stripeâ€™s officially supported Client libraries support sending
        <code>multipart/form-data</code>.</p>
      tags:
        - V1
        - Files
  /v1/files/{file}:
    get:
      description: >-
        <p>Retrieves the details of an existing file object. After you supply a
        unique file ID, Stripe returns the corresponding file object. Learn how
        to <a href="/docs/file-upload#download-file-contents">access file
        content
      tags:
        - V1
        - Files
        - Fi
