openapi: 3.0.0
info:
  title: Stripe Link API
paths:
  /v1/link_account_sessions:
    post:
      description: >-
        <p>To launch the Financial Connections authorization flow, create a
        <code>Session</code>. The sessionâ€™s <code>client_secret</code> can be
        used to launch the flow using Stripe.js.</p>
      summary: Launch Link Account Session
      tags:
        - Launch
        - Link
        - Account
        - Session
        - V1
        - Link_account_sessions
  /v1/link_account_sessions/{session}:
    get:
      description: >-
        <p>Retrieves the details of a Financial Connections
        <code>Session</code></p>
      summary: Retrieve Link Account Session
      tags:
        - Retrieve
        - Link
        - Account
        - Session
        - V1
        - Link_account_sessions
        - Session
  /v1/linked_accounts:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Account</code>
        objects.</p>
      summary: Retrieve Link Accounts
      tags:
        - Retrieve
        - Link
        - Accounts
        - V1
        - Link_account_sessions
        - Session
        - Linked_accounts
  /v1/linked_accounts/{account}:
    get:
      description: >-
        <p>Retrieves the details of an Financial Connections
        <code>Account</code>.</p>
      summary: Retrieve Link Account
      tags:
        - Retrieve
        - Link
        - Account
        - V1
        - Link_account_sessions
        - Session
        - Linked_accounts
        - Account
  /v1/linked_accounts/{account}/disconnect:
    post:
      description: >-
        <p>Disables your access to a Financial Connections <code>Account</code>.
        You will no longer be able to access data associated with the account
        (e.g. balances, transactions).</p>
      summary: Disconnect Link Accounts
      tags:
        - Disconnect
        - Link
        - Accounts
        - V1
        - Link_account_sessions
        - Session
        - Linked_accounts
        - Account
        - Disconnect
  /v1/linked_accounts/{account}/owners:
    get:
      description: <p>Lists all owners for a given <code>Account</code></p>
      summary: Retrieve Link Account Owners
      tags:
        - Retrieve
        - Link
        - Account
        - Owners
        - V1
        - Link_account_sessions
        - Session
        - Linked_accounts
        - Account
        - Disconnect
        - Owners
  /v1/linked_accounts/{account}/refresh:
    post:
      description: >-
        <p>Refreshes the data associated with a Financial Connections
        <code>Account</code>.</p>
      summary: Refresh Link Account
      tags:
        - Refresh
        - Link
        - Account
        - V1
        - Link_account_sessions
        - Session
        - Linked_accounts
        - Account
        - Disconnect
        - Owners
        - Refresh
tags:
  - name: Links
    description: Needs a description.
  - name: Accounts
    description: Needs a description.
  - name: Sessions
    description: Needs a description.
  - name: Disconnect
    description: Needs a description.
  - name: Owners
    description: Needs a description.
  - name: Refresh
    description: Needs a descriptio
