openapi: 3.0.0
info:
  title: Stripe Payouts API
paths:
  /v1/payouts:
    get:
      description: >-
        <p>Returns a list of existing payouts sent to third-party bank accounts
        or payouts that Stripe sent to you. The payouts return in sorted order,
        with the most recently created payouts appearing first.</p>
      tags:
        - V1
        - Payouts
    post:
      description: >-
        <p>To send funds to your own bank account, create a new payout object.
        Your <a href="#balance">Stripe balance</a> must cover the payout amount.
        If it doesn’t, you receive an “Insufficient Funds” error.</p>


        <p>If your API key is in test mode, money won’t actually be sent, though
        every other action occurs as if you’re in live mode.</p>


        <p>If you create a manual payout on a Stripe account that uses multiple
        payment source types, you need to specify the source type balance that
        the payout draws from. The <a href="#balance_object">balance object</a>
        details available and pending amounts by source type.</p>
      tags:
        - V1
        - Payouts
  /v1/payouts/{payout}:
    get:
      description: >-
        <p>Retrieves the details of an existing payout. Supply the unique payout
        ID from either a payout creation request or the payout list. Stripe
        returns the corresponding payout information.</p>
      tags:
        - V1
        - Payouts
        - Payout
    post:
      description: >-
        <p>Updates the specified payout by setting the values of the parameters
        you pass. We don’t change parameters that you don’t provide. This
        request only accepts the metadata as arguments.</p>
      tags:
        - V1
        - Payouts
        - Payout
  /v1/payouts/{payout}/cancel:
    post:
      description: >-
        <p>You can cancel a previously created payout if it hasn’t been paid out
        yet. Stripe refunds the funds to your available balance. You can’t
        cancel automatic Stripe payouts.</p>
      tags:
        - V1
        - Payouts
        - Payout
        - Cancel
  /v1/payouts/{payout}/reverse:
    post:
      description: >-
        <p>Reverses a payout by debiting the destination bank account. At this
        time, you can only reverse payouts for connected accounts to US bank
        accounts. If the payout is in the <code>pending</code> status, use
        <code>/v1/payouts/:id/cancel</code> instead.</p>


        <p>By requesting a reversal through
        <code>/v1/payouts/:id/reverse</code>, you confirm that the authorized
        signatory of the selected bank account authorizes the debit on the bank
        account and that no other authorization is req
      tags:
        - V1
        - Payouts
        - Payout
        - Cancel
        - Rever
