openapi: 3.0.0
info:
  title: Stripe Prices API
paths:
  /v1/prices:
    get:
      description: >-
        <p>Returns a list of your active prices, excluding <a
        href="/docs/products-prices/pricing-models#inline-pricing">inline
        prices</a>. For the list of inactive prices, set <code>active</code> to
        false.</p>
      tags:
        - V1
        - Prices
    post:
      description: >-
        <p>Creates a new price for an existing product. The price can be
        recurring or one-time.</p>
      tags:
        - V1
        - Prices
  /v1/prices/search:
    get:
      description: >-
        <p>Search for prices you’ve previously created using Stripe’s <a
        href="/docs/search#search-query-language">Search Query Language</a>.

        Don’t use search in read-after-write flows where strict consistency is
        necessary. Under normal operating

        conditions, data is searchable in less than a minute. Occasionally,
        propagation of new or updated data can be up

        to an hour behind during outages. Search functionality is not available
        to merchants in India.</p>
      tags:
        - V1
        - Prices
        - Search
  /v1/prices/{price}:
    get:
      description: <p>Retrieves the price with the given ID.</p>
      tags:
        - V1
        - Prices
        - Search
        - Price
    post:
      description: >-
        <p>Updates the specified price by setting the values of the parameters
        passed. Any parameters not provided are left unch
      tags:
        - V1
        - Prices
        - Search
        - Pri
