openapi: 3.0.0
info:
  title: Stripe Promotion Codes API
paths:
  /v1/promotion_codes:
    get:
      description: <p>Returns a list of your promotion codes.</p>
      summary: Retrieve Promotion Codes
      tags:
        - Retrieve
        - Promotion
        - Codes
        - V1
        - Promotion_codes
    post:
      description: >-
        <p>A promotion code points to a coupon. You can optionally restrict the
        code to a specific customer, redemption limit, and expiration date.</p>
      summary: Create Promotion Code
      tags:
        - Create
        - Promotion
        - Code
        - V1
        - Promotion_codes
  /v1/promotion_codes/{promotion_code}:
    get:
      description: >-
        <p>Retrieves the promotion code with the given ID. In order to retrieve
        a promotion code by the customer-facing <code>code</code> use <a
        href="/docs/api/promotion_codes/list">list</a> with the desired
        <code>code</code>.</p>
      summary: Retrieve Promotion Code
      tags:
        - Retrieve
        - Promotion
        - Code
        - V1
        - Promotion_codes
        - Promotion_code
    post:
      description: >-
        <p>Updates the specified promotion code by setting the values of the
        parameters passed. Most fields are, by design, not editable.</p>
      summary: Update Promotion Code
      tags:
        - Update
        - Promotion
        - Code
        - V1
        - Promotion_codes
        - Promotion_code
tags:
  - name: Promotions
    description: Needs a description.
  - name: Codes
    description: Needs a descriptio
