openapi: 3.0.0
info:
  title: Stripe Refunds API
paths:
  /v1/refunds:
    get:
      description: >-
        <p>Returns a list of all refunds you created. We return the refunds in
        sorted order, with the most recent refunds appearing first The 10 most
        recent refunds are always available by default on the Charge object.</p>
    post:
      description: >-
        <p>When you create a new refund, you must specify a Charge or a
        PaymentIntent object on which to create it.</p>


        <p>Creating a new refund will refund a charge that has previously been
        created but not yet refunded.

        Funds will be refunded to the credit or debit card that was originally
        charged.</p>


        <p>You can optionally refund only part of a charge.

        You can do so multiple times, until the entire charge has been
        refunded.</p>


        <p>Once entirely refunded, a charge can’t be refunded again.

        This method will raise an error when called on an already-refunded
        charge,

        or when trying to refund more money than is left on a charge.</p>
  /v1/refunds/{refund}:
    get:
      description: <p>Retrieves the details of an existing refund.</p>
    post:
      description: >-
        <p>Updates the refund that you specify by setting the values of the
        passed parameters. Any parameters that you don’t provide remain
        unchanged.</p>


        <p>This request only accepts <code>metadata</code> as an argument.</p>
  /v1/refunds/{refund}/cancel:
    post:
      description: >-
        <p>Cancels a refund with a status of <code>requires_action</code>.</p>


        <p>You can’t cancel refunds in other states. Only refunds for payment
        methods that require customer action can enter the
        <code>requires_action</code> st
