info:
  title: acm
paths:
  /:
    POST:
      summary: Update Certificate Options
      description: >-
        <p>Updates a certificate. Currently, you can use this function to
        specify whether to opt in to or out of recording your certificate in a
        certificate transparency log. For more information, see <a
        href="https://docs.aws.amazon.com/acm/latest/userguide/acm-bestpractices.html#best-practices-transparency">
        Opting Out of Certificate Transparency Logging</a>. </p>
components: {}
