openapi: 3.1.0
info:
  title: appflow
paths:
  /cancel-flow-executions:
    POST:
      summary: CancelFlowExecutions
      description: >-
        <p>Cancels active runs for a flow.</p> <p>You can cancel all of the
        active runs for a flow, or you can cancel specific runs by providing
        their IDs.</p> <p>You can cancel a flow run only when the run is in
        progress. You can't cancel a run that has already completed or failed.
        You also can't cancel a run that's scheduled to occur but hasn't started
        yet. To prevent a scheduled run, you can deactivate the flow with the
        <code>StopFlow</code> action.</p> <p>You cannot resume a run after you
        cancel it.</p> <p>When you send your request, the status for each run
        becomes <code>CancelStarted</code>. When the cancellation completes, the
        status becomes <code>Canceled</code>.</p> <note> <p>When you cancel a
        run, you still incur charges for any data that the run already processed
        before the cancellation. If the run had already written some data to the
        flow destination, then that data remains in the destination. If you
        configured the flow to use a batch API (such as the Salesforce Bulk API
        2.0), then the run will finish reading or writing its entire batch of
        data after the cancellation. For these operations, the data processing
        charges for Amazon AppFlow apply. For the pricing information, see <a
        href="http://aws.amazon.com/appflow/pricing/">Amazon AppFlow
        pricing</a>.</p> </note>
      tags:
        - Cancel
        - Flow
        - Executions
        - Cancel
        - Flow
        - Executions
  /create-connector-profile:
    POST:
      summary: CreateConnectorProfile
      description: >-
        <p> Creates a new connector profile associated with your Amazon Web
        Services account. There is a soft quota of 100 connector profiles per
        Amazon Web Services account. If you need more connector profiles than
        this quota allows, you can submit a request to the Amazon AppFlow team
        through the Amazon AppFlow support channel. In each connector profile
        that you create, you can provide the credentials and properties for only
        one connector.</p>
      tags:
        - Create
        - Connector
        - Profile
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
  /create-flow:
    POST:
      summary: CreateFlow
      description: >-
        <p> Enables your application to create a new flow using Amazon AppFlow.
        You must create a connector profile before calling this API. Please note
        that the Request Syntax below shows syntax for multiple destinations,
        however, you can only transfer data to one item in this list at a time.
        Amazon AppFlow does not currently support flows to multiple destinations
        at once. </p>
      tags:
        - Create
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
  /delete-connector-profile:
    POST:
      summary: DeleteConnectorProfile
      description: <p> Enables you to delete an existing connector profile. </p>
      tags:
        - Delete
        - Connector
        - Profile
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
  /delete-flow:
    POST:
      summary: DeleteFlow
      description: >-
        <p> Enables your application to delete an existing flow. Before deleting
        the flow, Amazon AppFlow validates the request by checking the flow
        configuration and status. You can delete flows one at a time. </p>
      tags:
        - Delete
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
  /describe-connector:
    POST:
      summary: DescribeConnector
      description: >-
        <p>Describes the given custom connector registered in your Amazon Web
        Services account. This API can be used for custom connectors that are
        registered in your account and also for Amazon authored connectors.</p>
      tags:
        - Describe
        - Connector
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
  /describe-connector-entity:
    POST:
      summary: DescribeConnectorEntity
      description: >-
        <p> Provides details regarding the entity used with the connector, with
        a description of the data model for each field in that entity. </p>
      tags:
        - Describe
        - Connector
        - Entity
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
  /describe-connector-profiles:
    POST:
      summary: DescribeConnectorProfiles
      description: >-
        <p> Returns a list of <code>connector-profile</code> details matching
        the provided <code>connector-profile</code> names and
        <code>connector-types</code>. Both input lists are optional, and you can
        use them to filter the result. </p> <p>If no names or
        <code>connector-types</code> are provided, returns all connector
        profiles in a paginated form. If there is no match, this operation
        returns an empty list.</p>
      tags:
        - Describe
        - Connector
        - Profiles
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
  /describe-connectors:
    POST:
      summary: DescribeConnectors
      description: >-
        <p> Describes the connectors vended by Amazon AppFlow for specified
        connector types. If you don't specify a connector type, this operation
        describes all connectors vended by Amazon AppFlow. If there are more
        connectors than can be returned in one page, the response contains a
        <code>nextToken</code> object, which can be be passed in to the next
        call to the <code>DescribeConnectors</code> API operation to retrieve
        the next page. </p>
      tags:
        - Describe
        - Connectors
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
  /describe-flow:
    POST:
      summary: DescribeFlow
      description: <p> Provides a description of the specified flow. </p>
      tags:
        - Describe
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
  /describe-flow-execution-records:
    POST:
      summary: DescribeFlowExecutionRecords
      description: <p> Fetches the execution history of the flow. </p>
      tags:
        - Describe
        - Flow
        - Execution
        - Records
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
  /list-connector-entities:
    POST:
      summary: ListConnectorEntities
      description: >-
        <p> Returns the list of available connector entities supported by Amazon
        AppFlow. For example, you can query Salesforce for <i>Account</i> and
        <i>Opportunity</i> entities, or query ServiceNow for the <i>Incident</i>
        entity. </p>
      tags:
        - List
        - Connector
        - Entities
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
  /list-connectors:
    POST:
      summary: ListConnectors
      description: >-
        <p>Returns the list of all registered custom connectors in your Amazon
        Web Services account. This API lists only custom connectors registered
        in this account, not the Amazon Web Services authored connectors. </p>
      tags:
        - List
        - Connectors
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
  /list-flows:
    POST:
      summary: ListFlows
      description: <p> Lists all of the flows associated with your account. </p>
      tags:
        - List
        - Flows
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p> Removes a tag from the specified flow. </p>
      tags:
        - Untag
        - Resource
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
  /register-connector:
    POST:
      summary: RegisterConnector
      description: >-
        <p>Registers a new custom connector with your Amazon Web Services
        account. Before you can register the connector, you must deploy the
        associated AWS lambda function in your account.</p>
      tags:
        - Register
        - Connector
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
  /reset-connector-metadata-cache:
    POST:
      summary: ResetConnectorMetadataCache
      description: >-
        <p>Resets metadata about your connector entities that Amazon AppFlow
        stored in its cache. Use this action when you want Amazon AppFlow to
        return the latest information about the data that you have in a source
        application.</p> <p>Amazon AppFlow returns metadata about your entities
        when you use the ListConnectorEntities or DescribeConnectorEntities
        actions. Following these actions, Amazon AppFlow caches the metadata to
        reduce the number of API requests that it must send to the source
        application. Amazon AppFlow automatically resets the cache once every
        hour, but you can use this action when you want to get the latest
        metadata right away.</p>
      tags:
        - Reset
        - Connector
        - Metadata
        - Cache
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
  /start-flow:
    POST:
      summary: StartFlow
      description: >-
        <p> Activates an existing flow. For on-demand flows, this operation runs
        the flow immediately. For schedule and event-triggered flows, this
        operation activates the flow. </p>
      tags:
        - Start
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
  /stop-flow:
    POST:
      summary: StopFlow
      description: >-
        <p> Deactivates the existing flow. For on-demand flows, this operation
        returns an <code>unsupportedOperationException</code> error message. For
        schedule and event-triggered flows, this operation deactivates the flow.
        </p>
      tags:
        - Stop
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
        - Stop
  /unregister-connector:
    POST:
      summary: UnregisterConnector
      description: >-
        <p>Unregisters the custom connector registered in your account that
        matches the connector label provided in the request.</p>
      tags:
        - Unregister
        - Connector
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
        - Stop
        - Unregister
  /update-connector-profile:
    POST:
      summary: UpdateConnectorProfile
      description: <p> Updates a given connector profile associated with your account. </p>
      tags:
        - Update
        - Connector
        - Profile
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
        - Stop
        - Unregister
        - Update
  /update-connector-registration:
    POST:
      summary: UpdateConnectorRegistration
      description: >-
        <p>Updates a custom connector that you've previously registered. This
        operation updates the connector with one of the following:</p> <ul> <li>
        <p>The latest version of the AWS Lambda function that's assigned to the
        connector</p> </li> <li> <p>A new AWS Lambda function that you
        specify</p> </li> </ul>
      tags:
        - Update
        - Connector
        - Registration
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
        - Stop
        - Unregister
        - Update
        - Registration
  /update-flow:
    POST:
      summary: UpdateFlow
      description: <p> Updates an existing
      tags:
        - Update
        - Flow
        - Cancel
        - Flow
        - Executions
        - Create
        - Connector
        - Profile
        - Delete
        - Describe
        - Entity
        - Profiles
        - Connectors
        - Execution
        - Records
        - List
        - Entities
        - Flows
        - Arn
        - Register
        - Reset
        - Metadata
        - Cache
        - Start
        - Stop
        - Unregister
        - Update
        - Registrati
