openapi: 3.1.0
info:
  title: application-autoscaling
paths:
  /:
    POST:
      summary: UntagResource
      description: >-
        <p>Deletes tags from an Application Auto Scaling scalable target. To
        delete a tag, specify the tag key and the Application Auto Scaling
        scalable target.</
      tags:
        - Untag
        - Resource
