openapi: 3.1.0
info:
  title: applicationcostprofiler
paths:
  /reportDefinition/{reportId}:
    PUT:
      summary: UpdateReportDefinition
      description: <p>Updates existing report in AWS Application Cost Profiler.</p>
      tags:
        - Update
        - Report
        - Definition
        - Definition
        - Report
        - Id
  /importApplicationUsage:
    POST:
      summary: ImportApplicationUsage
      description: >-
        <p>Ingests application usage data from Amazon Simple Storage Service
        (Amazon S3).</p> <p>The data must already exist in the S3 location. As
        part of the action, AWS Application Cost Profiler copies the object from
        your S3 bucket to an S3 bucket owned by Amazon for processing
        asynchronously.</p>
      tags:
        - Import
        - Application
        - Usage
        - Definition
        - Report
        - Id
        - Application
        - Usage
  /reportDefinition:
    POST:
      summary: PutReportDefinition
      description: <p>Creates the report definition for a report in Application Cost Pro
      tags:
        - Put
        - Report
        - Definition
        - Definition
        - Report
        - Id
        - Application
        - Usa
