openapi: 3.1.0
info:
  title: appmesh
paths:
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes:
    GET:
      summary: ListGatewayRoutes
      description: >-
        <p>Returns a list of existing gateway routes that are associated to a
        virtual gateway.</p>
      tags:
        - Lists
        - Gateway
        - Routes
        - Names
        - Virtual
        - Gateway
        - Routes
  /v20190125/meshes:
    GET:
      summary: ListMeshes
      description: <p>Returns a list of existing service meshes.</p>
      tags:
        - Lists
        - Meshes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes:
    GET:
      summary: ListRoutes
      description: <p>Returns a list of existing routes in a service mesh.</p>
      tags:
        - Lists
        - Routes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
  /v20190125/meshes/{meshName}/virtualGateways:
    GET:
      summary: ListVirtualGateways
      description: <p>Returns a list of existing virtual gateways in a service mesh.</p>
      tags:
        - Lists
        - Virtual
        - Gateways
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
  /v20190125/meshes/{meshName}/virtualNodes:
    GET:
      summary: ListVirtualNodes
      description: <p>Returns a list of existing virtual nodes.</p>
      tags:
        - Lists
        - Virtual
        - Nodes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
  /v20190125/meshes/{meshName}/virtualRouters:
    GET:
      summary: ListVirtualRouters
      description: <p>Returns a list of existing virtual routers in a service mesh.</p>
      tags:
        - Lists
        - Virtual
        - Routers
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
  /v20190125/meshes/{meshName}/virtualServices:
    GET:
      summary: ListVirtualServices
      description: <p>Returns a list of existing virtual services in a service mesh.</p>
      tags:
        - Lists
        - Virtual
        - Services
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes/{gatewayRouteName}:
    PUT:
      summary: UpdateGatewayRoute
      description: >-
        <p>Updates an existing gateway route that is associated to a specified
        virtual gateway in a service mesh.</p>
      tags:
        - Update
        - Gateway
        - Routes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
  /v20190125/meshes/{meshName}:
    PUT:
      summary: UpdateMesh
      description: <p>Updates an existing service mesh.</p>
      tags:
        - Update
        - Mesh
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes/{routeName}:
    PUT:
      summary: UpdateRoute
      description: >-
        <p>Updates an existing route for a specified service mesh and virtual
        router.</p>
      tags:
        - Update
        - Routes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
  /v20190125/meshes/{meshName}/virtualGateways/{virtualGatewayName}:
    PUT:
      summary: UpdateVirtualGateway
      description: <p>Updates an existing virtual gateway in a specified service mesh.</p>
      tags:
        - Update
        - Virtual
        - Gateway
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
  /v20190125/meshes/{meshName}/virtualNodes/{virtualNodeName}:
    PUT:
      summary: UpdateVirtualNode
      description: <p>Updates an existing virtual node in a specified service mesh.</p>
      tags:
        - Update
        - Virtual
        - Nodes
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
  /v20190125/meshes/{meshName}/virtualRouters/{virtualRouterName}:
    PUT:
      summary: UpdateVirtualRouter
      description: <p>Updates an existing virtual router in a specified service mesh.</p>
      tags:
        - Update
        - Virtual
        - Router
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
  /v20190125/meshes/{meshName}/virtualServices/{virtualServiceName}:
    PUT:
      summary: UpdateVirtualService
      description: <p>Updates an existing virtual service in a specified service mesh.</p>
      tags:
        - Update
        - Virtual
        - Services
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
        - Services
  /v20190125/tags:
    GET:
      summary: ListTagsForResource
      description: <p>List the tags for an App Mesh resource.</p>
      tags:
        - Lists
        - Tags
        - For
        - Resources
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
        - Services
        - Tags
  /v20190125/tag:
    PUT:
      summary: TagResource
      description: >-
        <p>Associates the specified tags to a resource with the specified
        <code>resourceArn</code>. If existing tags on a resource aren't
        specified in the request parameters, they aren't changed. When a
        resource is deleted, the tags associated with that resource are also
        deleted.</p>
      tags:
        - Tags
        - Resources
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
        - Services
        - Tags
        - Tags
  /v20190125/untag:
    PUT:
      summary: UntagResource
      description: <p>Deletes specified tags from a res
      tags:
        - Untag
        - Resources
        - Names
        - Virtual
        - Gateway
        - Routes
        - V20190125
        - Meshes
        - Router
        - Gateways
        - Nodes
        - Routers
        - Services
        - Routes
        - Nodes
        - Services
        - Tags
        - Tags
        - Unt
