openapi: 3.1.0
info:
  title: apprunner
paths:
  /:
    POST:
      summary: UpdateVpcIngressConnection
      description: >-
        <p>Update an existing App Runner VPC Ingress Connection resource. The
        VPC Ingress Connection must be in one of the following states to be
        updated:</p> <ul> <li> <p> AVAILABLE </p> </li> <li> <p> FAILED_CREATION
        </p> </li> <li> <p> FAILED_UPDATE </p> </li> </u
      tags:
        - Update
        - Vpc
        - Ingress
        - Connection
