openapi: 3.1.0
info:
  title: appstream
paths:
  /:
    POST:
      summary: UpdateStack
      description: <p>Updates the specified fields for the specified stack.</
      tags:
        - Update
        - null
