openapi: 3.1.0
info:
  title: b2bi
paths:
  /:
    POST:
      summary: UpdateTransformer
      description: >-
        <p>Updates the specified parameters for a transformer. A transformer
        describes how to process the incoming EDI documents and extract the
        necessary information to the output f
