openapi: 3.1.0
info:
  title: ce
paths:
  /:
    POST:
      summary: UpdateCostCategoryDefinition
      description: >-
        <p>Updates an existing Cost Category. Changes made to the Cost Category
        rules will be used to categorize the current month’s expenses and future
        expenses. This won’t change categorization for the previous mon
