openapi: 3.1.0
info:
  title: cloudsearch
paths:
  /:
    POST:
      summary: UpdateServiceAccessPolicies
      description: >-
        <p>Configures the access rules that control access to the domain's
        document and search endpoints. For more information, see <a
        href="http://docs.aws.amazon.com/cloudsearch/latest/developerguide/configuring-access.html"
        target="_blank"> Configuring Access for an Amazon CloudSearch Domai
      tags:
        - Update
        - Service
        - Access
        - Polici
