openapi: 3.1.0
info:
  title: cloudhsmv2
paths:
  /:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes the specified tag or tags from the specified AWS CloudHSM
        cluster.</
      tags:
        - Untag
        - Re
