openapi: 3.1.0
info:
  title: cloudtrail-data
paths:
  /PutAuditEvents:
    POST:
      summary: PutAuditEvents
      description: >-
        <p>Ingests your application events into CloudTrail Lake. A required
        parameter, <code>auditEvents</code>, accepts the JSON records (also
        called <i>payload</i>) of events that you want CloudTrail to ingest. You
        can add up to 100 of these events (or up to 1 MB) per
        <code>PutAuditEvents</code> request.</
      tags:
        - Put
        - Audit
        - Events
        - Put
        - Audit
        - Events
