openapi: 3.1.0
info:
  title: cloudformation
paths:
  /:
    POST:
      summary: ValidateTemplate
      description: >-
        <p>Validates a specified template. CloudFormation first checks if the
        template is valid JSON. If it isn't, CloudFormation checks if the
        template is valid YAML. If both these checks fail, CloudFormation
        returns a template validation error.</
      tags:
        - Validate
        - Te
