openapi: 3.1.0
info:
  title: codecommit
paths:
  /:
    POST:
      summary: UpdateRepositoryName
      description: >-
        <p>Renames a repository. The repository name must be unique across the
        calling Amazon Web Services account. Repository names are limited to 100
        alphanumeric, dash, and underscore characters, and cannot include
        certain characters. The suffix .git is prohibited. For more information
        about the limits on repository names, see <a
        href="https://docs.aws.amazon.com/codecommit/latest/userguide/limits.html">Quotas</a>
        in the CodeCommit User 
      tags:
        - Update
        - Repositories
        - Names
