openapi: 3.1.0
info:
  title: codebuild
paths:
  /:
    POST:
      summary: UpdateWebhook
      description: >-
        <p> Updates the webhook associated with an CodeBuild build project. </p>
        <note> <p> If you use Bitbucket for your repository,
        <code>rotateSecret</code> is ignored. </p>
