openapi: 3.1.0
info:
  title: codestar-notifications
paths:
  /createNotificationRule:
    POST:
      summary: CreateNotificationRule
      description: >-
        <p>Creates a notification rule for a resource. The rule specifies the
        events you want notifications about and the targets (such as Chatbot
        topics or Chatbot clients configured for Slack) where you want to
        receive them.</p>
      tags:
        - Create
        - Notifications
        - Rules
        - Notifications
        - Rules
  /deleteNotificationRule:
    POST:
      summary: DeleteNotificationRule
      description: <p>Deletes a notification rule for a resource.</p>
      tags:
        - Delete
        - Notifications
        - Rules
        - Notifications
        - Rules
  /deleteTarget:
    POST:
      summary: DeleteTarget
      description: <p>Deletes a specified target for notifications.</p>
      tags:
        - Delete
        - Target
        - Notifications
        - Rules
        - Target
  /describeNotificationRule:
    POST:
      summary: DescribeNotificationRule
      description: <p>Returns information about a specified notification rule.</p>
      tags:
        - Describe
        - Notifications
        - Rules
        - Notifications
        - Rules
        - Target
  /listEventTypes:
    POST:
      summary: ListEventTypes
      description: >-
        <p>Returns information about the event types available for configuring
        notifications.</p>
      tags:
        - Lists
        - Events
        - Types
        - Notifications
        - Rules
        - Target
        - Events
        - Types
  /listNotificationRules:
    POST:
      summary: ListNotificationRules
      description: >-
        <p>Returns a list of the notification rules for an Amazon Web Services
        account.</p>
      tags:
        - Lists
        - Notifications
        - Rules
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
  /listTagsForResource:
    POST:
      summary: ListTagsForResource
      description: <p>Returns a list of the tags associated with a notification rule.</p>
      tags:
        - Lists
        - Tags
        - For
        - Resources
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
  /listTargets:
    POST:
      summary: ListTargets
      description: >-
        <p>Returns a list of the notification rule targets for an Amazon Web
        Services account.</p>
      tags:
        - Lists
        - Targets
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
  /subscribe:
    POST:
      summary: Subscribe
      description: >-
        <p>Creates an association between a notification rule and an Chatbot
        topic or Chatbot client so that the associated target can receive
        notifications when the events described in the rule are triggered.</p>
      tags:
        - Subscribe
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
        - Subscribe
  /tagResource:
    POST:
      summary: TagResource
      description: <p>Associates a set of provided tags with a notification rule.</p>
      tags:
        - Tags
        - Resources
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
        - Subscribe
  /unsubscribe:
    POST:
      summary: Unsubscribe
      description: >-
        <p>Removes an association between a notification rule and an Chatbot
        topic so that subscribers to that topic stop receiving notifications
        when the events described in the rule are triggered.</p>
      tags:
        - Unsubscribe
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
        - Subscribe
        - Unsubscribe
  /untagResource/{resourceArn}:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes the association between one or more provided tags and a
        notification rule.</p>
      tags:
        - Untag
        - Resources
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
        - Subscribe
        - Unsubscribe
        - ARN
  /updateNotificationRule:
    POST:
      summary: UpdateNotificationRule
      description: >-
        <p>Updates a notification rule for a resource. You can change the events
        that trigger the notification rule, the status of the rule, and the
        targets that receive the notifications.</p> <note> <p>To add or remove
        tags for a notification rule, you must use <a>TagResource</a> and
        <a>UntagResource</a>.</
      tags:
        - Update
        - Notifications
        - Rules
        - Notifications
        - Rules
        - Target
        - Events
        - Types
        - Rules
        - Tags
        - For
        - Resources
        - Targets
        - Subscribe
        - Unsubscribe
        - A
