openapi: 3.1.0
info:
  title: codepipeline
paths:
  /:
    POST:
      summary: UpdatePipeline
      description: >-
        <p>Updates a specified pipeline with edits or changes to its structure.
        Use a JSON file with the pipeline structure and
        <code>UpdatePipeline</code> to provide the full structure of the
        pipeline. Updating the pipeline increases the version number of the
        pipeline b
