openapi: 3.1.0
info:
  title: cognito-idp
paths:
  /:
    POST:
      summary: VerifyUserAttribute
      description: >-
        <p>Verifies the specified user attributes in the user pool.</p> <p> If
        your user pool requires verification before Amazon Cognito updates the
        attribute value, VerifyUserAttribute updates the affected attribute to
        its pending value. For more information, see <a
        href="https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserAttributeUpdateSettingsType.html">
        UserAttributeUpdateSettingsType</a>. </p> <p>Authorize this action with
        a signed-in user's access token. It must include the scope
        <code>aws.cognito.signin.user.admin</code>.</p> <note> <p>Amazon Cognito
        doesn't evaluate Identity and Access Management (IAM) policies in
        requests for this API operation. For this operation, you can't use IAM
        credentials to authorize requests, and you can't grant IAM permissions
        in policies. For more information about authorization models in Amazon
        Cognito, see <a
        href="https://docs.aws.amazon.com/cognito/latest/developerguide/user-pools-API-operations.html">Using
        the Amazon Cognito user pools API and user pool endpoints</a>.</p>
