openapi: 3.1.0
info:
  title: cognito-identity
paths:
  /:
    POST:
      summary: UpdateIdentityPool
      description: >-
        <p>Updates an identity pool.</p> <p>You must use AWS Developer
        credentials to call this API.</
      tags:
        - Update
        - Identity
        - nu
