openapi: 3.1.0
info:
  title: compute-optimizer
paths:
  /:
    POST:
      summary: UpdateEnrollmentStatus
      description: >-
        <p>Updates the enrollment (opt in and opt out) status of an account to
        the Compute Optimizer service.</p> <p>If the account is a management
        account of an organization, this action can also be used to enroll
        member accounts of the organization.</p> <p>You must have the
        appropriate permissions to opt in to Compute Optimizer, to view its
        recommendations, and to opt out. For more information, see <a
        href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/security-iam.html">Controlling
        access with Amazon Web Services Identity and Access Management</a> in
        the <i>Compute Optimizer User Guide</i>.</p> <p>When you opt in, Compute
        Optimizer automatically creates a service-linked role in your account to
        access its data. For more information, see <a
        href="https://docs.aws.amazon.com/compute-optimizer/latest/ug/using-service-linked-roles.html">Using
        Service-Linked Roles for Compute Optimizer</a> in the <i>Compute
        Optimizer User Guide</i>.</
      tags:
        - Update
        - Enrollment
        - null
