openapi: 3.1.0
info:
  title: cost-optimization-hub
paths:
  /:
    POST:
      summary: UpdatePreferences
      description: >-
        <p>Updates a set of preferences for an account in order to add
        account-specific preferences into the service. These preferences impact
        how the savings associated with recommendations are presented.</
      tags:
        - Update
        - Prefe
