openapi: 3.1.0
info:
  title: cur
paths:
  /:
    POST:
      summary: UntagResource
      description: <p>Disassociates a set of tags from a report defin
      tags:
        - Untag
        - Resour
