openapi: 3.1.0
info:
  title: datasync
paths:
  /:
    POST:
      summary: UpdateTaskExecution
      description: >-
        <p>Updates the configuration of a running DataSync task execution.</p>
        <note> <p>Currently, the only <code>Option</code> that you can modify
        with <code>UpdateTaskExecution</code> is <code> <a
        href="https://docs.aws.amazon.com/datasync/latest/userguide/API_Options.html#DataSync-Type-Options-BytesPerSecond">BytesPerSecond</a>
        </code>, which throttles bandwidth for a running or queued task
        execution.</p> </not
      tags:
        - Update
        - Task
        - Execution
