openapi: 3.1.0
info:
  title: email
paths:
  /:
    POST:
      summary: VerifyEmailIdentity
      description: >-
        <p>Adds an email address to the list of identities for your Amazon SES
        account in the current Amazon Web Services Region and attempts to verify
        it. As a result of executing this operation, a verification email is
        sent to the specified address.</p> <p>You can execute this operation no
        more than once per sec
