openapi: 3.1.0
info:
  title: eventbridge
paths:
  /:
    POST:
      summary: UpdateEndpoint
      description: >-
        <p>Update an existing endpoint. For more information about global
        endpoints, see <a
        href="https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-global-endpoints.html">Making
        applications Regional-fault tolerant with global endpoints and event
        replication</a> in the <i>Amazon EventBridge User Guid
      tags:
        - Update
        - Endpoi
