openapi: 3.1.0
info:
  title: kinesis-video-webrtc-storage
paths:
  /joinStorageSession:
    POST:
      summary: JoinStorageSession
      description: >-
        <p> Join the ongoing one way-video and/or multi-way audio WebRTC session
        as a video producing device for an input channel. If thereâ€™s no existing
        session for the channel, a new streaming session needs to be created,
        and the Amazon Resource Name (ARN) of the signaling channel must be
        provided. </p> <p>Currently for the <code>SINGLE_MASTER</code> type, a
        video producing device is able to ingest both audio and video media into
        a stream, while viewers can only ingest audio. Both a video producing
        device and viewers can join the session first, and wait for other
        participants.</p> <p>While participants are having peer to peer
        conversations through webRTC, the ingested media session will be stored
        into the Kinesis Video Stream. Multiple viewers are able to playback
        real-time media.</p> <p>Customers can also use existing Kinesis Video
        Streams features like <code>HLS</code> or <code>DASH</code> playback,
        Image generation, and more with ingested WebRTC media.</p> <note>
        <p>Assume that only one video producing device client can be associated
        with a session for the channel. If more than one client joins the
        session of a specific channel as a video producing device, the most
        recent client request takes precedence. </
      tags:
        - Join
        - Storage
        - Sessions
        - Storage
        - Sessions
