openapi: 3.1.0
info:
  title: sdb
paths:
  /:
    POST:
      summary: Select
      description: >-
        <p> The <code>Select</code> operation returns a set of attributes for
        <code>ItemNames</code> that match the select expression.
        <code>Select</code> is similar to the standard SQL SELECT statement.
        </p> <p> The total size of the response cannot exceed 1 MB in total
        size. Amazon SimpleDB automatically adjusts the number of items returned
        per page to enforce this limit. For example, if the client asks to
        retrieve 2500 items, but each individual item is 10 kB in size, the
        system returns 100 items and an appropriate <code>NextToken</code> so
        the client can access the next page of results. </p> <p> For information
        on how to construct select expressions, see Using Select to Create
        Amazon SimpleDB Queries in the Developer G
      tags:
        - Sele
