openapi: 3.1.0
info:
  title: vpc-lattice
paths:
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules:
    GET:
      summary: ListRules
      description: <p>Lists the rules for the listener.</p>
      tags:
        - Lists
        - Rules
        - Identifiers
        - Listeners
        - Listeners
        - Rules
  /accesslogsubscriptions:
    GET:
      summary: ListAccessLogSubscriptions
      description: >-
        <p>Lists all access log subscriptions for the specified service network
        or service.</p>
      tags:
        - Lists
        - Access
        - Logs
        - Subscriptions
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
  /services/{serviceIdentifier}/listeners:
    GET:
      summary: ListListeners
      description: <p>Lists the listeners for the specified service.</p>
      tags:
        - Lists
        - Listeners
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
  /services:
    GET:
      summary: ListServices
      description: >-
        <p>Lists the services owned by the caller account or shared with the
        caller account.</p>
      tags:
        - Lists
        - Services
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
  /servicenetworks:
    GET:
      summary: ListServiceNetworks
      description: >-
        <p>Lists the service networks owned by the caller account or shared with
        the caller account. Also includes the account ID in the ARN to show
        which account owns the service network.</p>
      tags:
        - Lists
        - Services
        - Networks
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
  /servicenetworkserviceassociations:
    GET:
      summary: ListServiceNetworkServiceAssociations
      description: >-
        <p>Lists the associations between the service network and the service.
        You can filter the list either by service or service network. You must
        provide either the service network identifier or the service
        identifier.</p> <p>Every association in Amazon VPC Lattice is given a
        unique Amazon Resource Name (ARN), such as when a service network is
        associated with a VPC or when a service is associated with a service
        network. If the association is for a resource that is shared with
        another account, the association will include the local account ID as
        the prefix in the ARN for each account the resource is shared with.</p>
      tags:
        - Lists
        - Services
        - Networks
        - Associations
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
  /servicenetworkvpcassociations:
    GET:
      summary: ListServiceNetworkVpcAssociations
      description: >-
        <p>Lists the service network and VPC associations. You can filter the
        list either by VPC or service network. You must provide either the
        service network identifier or the VPC identifier.</p>
      tags:
        - Lists
        - Services
        - Networks
        - VPC
        - Associations
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
  /targetgroups:
    GET:
      summary: ListTargetGroups
      description: >-
        <p>Lists your target groups. You can narrow your search by using the
        filters below in your request.</p>
      tags:
        - Lists
        - Target
        - Groups
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
  /accesslogsubscriptions/{accessLogSubscriptionIdentifier}:
    PATCH:
      summary: UpdateAccessLogSubscription
      description: <p>Updates the specified access log subscription.</p>
      tags:
        - Update
        - Access
        - Logs
        - Subscriptions
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
  /authpolicy/{resourceIdentifier}:
    PUT:
      summary: PutAuthPolicy
      description: <p>Creates or updates the auth policy.</p>
      tags:
        - Put
        - Authentication
        - Policies
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}:
    PATCH:
      summary: UpdateListener
      description: <p>Updates the specified listener for the specified service.</p>
      tags:
        - Update
        - Listeners
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
  /resourcepolicy/{resourceArn}:
    PUT:
      summary: PutResourcePolicy
      description: >-
        <p>Attaches a resource-based permission policy to a service or service
        network. The policy must contain the same actions and condition
        statements as the Amazon Web Services Resource Access Manager permission
        for sharing services and service networks.</p>
      tags:
        - Put
        - Resources
        - Policies
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules/{ruleIdentifier}:
    PATCH:
      summary: UpdateRule
      description: >-
        <p>Updates a rule for the listener. You can't modify a default listener
        rule. To modify a default listener rule, use
        <code>UpdateListener</code>.</p>
      tags:
        - Update
        - Rules
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
  /services/{serviceIdentifier}:
    PATCH:
      summary: UpdateService
      description: <p>Updates the specified service.</p>
      tags:
        - Update
        - Services
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
  /servicenetworks/{serviceNetworkIdentifier}:
    PATCH:
      summary: UpdateServiceNetwork
      description: <p>Updates the specified service network.</p>
      tags:
        - Update
        - Services
        - Networks
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
  /servicenetworkserviceassociations/{serviceNetworkServiceAssociationIdentifier}:
    GET:
      summary: GetServiceNetworkServiceAssociation
      description: >-
        <p>Retrieves information about the specified association between a
        service network and a service.</p>
      tags:
        - Get
        - Services
        - Networks
        - Association
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
  /servicenetworkvpcassociations/{serviceNetworkVpcAssociationIdentifier}:
    PATCH:
      summary: UpdateServiceNetworkVpcAssociation
      description: >-
        <p>Updates the service network and VPC association. Once you add a
        security group, it cannot be removed.</p>
      tags:
        - Update
        - Services
        - Networks
        - VPC
        - Association
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
  /targetgroups/{targetGroupIdentifier}:
    PATCH:
      summary: UpdateTargetGroup
      description: <p>Updates the specified target group.</p>
      tags:
        - Update
        - Target
        - Group
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
        - Group
  /targetgroups/{targetGroupIdentifier}/deregistertargets:
    POST:
      summary: DeregisterTargets
      description: >-
        <p>Deregisters the specified targets from the specified target
        group.</p>
      tags:
        - Deregister
        - Targets
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
        - Group
        - Deregister Targets
  /tags/{resourceArn}:
    DELETE:
      summary: UntagResource
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - Untag
        - Resources
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
        - Group
        - Deregister Targets
  /targetgroups/{targetGroupIdentifier}/listtargets:
    POST:
      summary: ListTargets
      description: >-
        <p>Lists the targets for the target group. By default, all targets are
        included. You can use this API to check the health status of targets.
        You can also Ô¨Ålter the results by target. </p>
      tags:
        - Lists
        - Targets
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
        - Group
        - Deregister Targets
        - Targets
  /targetgroups/{targetGroupIdentifier}/registertargets:
    POST:
      summary: RegisterTargets
      description: >-
        <p>Registers the targets with the target group. If it's a Lambda target,
        you can only have one target in a target 
      tags:
        - Register
        - Targets
        - Identifiers
        - Listeners
        - Listeners
        - Rules
        - Access Log Subscriptions
        - Services
        - Service Networks
        - Service Network Service Associations
        - Service Network VPC Associations
        - Target Groups
        - Logs
        - Subscriptions
        - ARN
        - Rules
        - Networks
        - Services
        - Association
        - VPC
        - Group
        - Deregister Targets
        - Targets
        - Registertarge
