weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-tags-object-error
    message: Tag Object
  - code: openapi-info-contact-error
    message: Contact Object
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-version-error
    message: Info Version
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation ID Camel Case
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-path-names-camel-case-error
    message: Parameter Path Name Camel Case
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-required-error
    message: Parameters MUST have a required property.
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-parameters-query-names-camel-case-error
    message: Parameter Query Name Camel Case
  - code: openapi-parameters-query-names-snake-case-error
    message: Parameter Query Name Snake Case
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-response-get-400-status-code-warn
    message: 400 Status Code for GET Responses
  - code: openapi-response-get-404-status-code-warn
    message: 404 Status Code for GET Responses
  - code: openapi-response-get-500-status-code-error
    message: 500 Status Code for GET Responses
  - code: openapi-response-get-200-status-code-info
    message: GET Response Has 200 Status Code
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-response-get-200-content-info
    message: GET Content
  - code: openapi-response-get-200-media-type-info
    message: JSON Media Type GET
  - code: openapi-response-get-200-media-type-schema-info
    message: Schema GET
  - code: openapi-response-get-200-schema-components-warn
    message: GET Response 200 Schema Components
  - code: openapi-response-get-200-schema-ref-warn
    message: GET Response 200 Schema Ref
  - code: openapi-response-get-default-status-code-info
    message: Response Has Default Status Code
  - code: openapi-response-get-default-content-info
    message: Default Content
  - code: openapi-response-get-default-media-type-info
    message: JSON Media Type Default
  - code: openapi-response-get-default-media-type-schema-info
    message: Schema Default
  - code: openapi-response-get-default-schema-ref-warn
    message: Default Response Schema Ref
  - code: openapi-request-body-on-put-info
    message: Request Body PUT
  - code: openapi-request-body-content-on-put-info
    message: Request Body Content PUT
  - code: openapi-request-body-have-content-info
    message: Request Body Content
  - code: openapi-request-body-have-application-json-info
    message: Request Body Application JSON
  - code: openapi-request-body-json-media-type-on-put-error
    message: JSON Media Type POSPUTT
  - code: openapi-request-body-json-media-type-on-put-info
    message: JSON Media Type PUT
  - code: openapi-request-body-have-schema-info
    message: Request Body Schema
  - code: openapi-request-body-schema-ref-warn
    message: Request Body Schema Ref
  - code: openapi-request-body-have-schema-properties-warn
    message: Request Body Schema Components
  - code: openapi-request-body-have-schema-required-info
    message: Request Body Schema Required
  - code: openapi-request-body-have-schema-required-warn
    message: Request Body Schema Required
  - code: openapi-request-body-schema-properties-format-error
    message: Request Body Schema Properties Format
  - code: openapi-request-body-schema-properties-names-pascal-case-error
    message: Request Body Schema Property Names Pascal Case
  - code: openapi-request-body-schema-properties-nullable-error
    message: Request Body Schema Properties Format
  - code: openapi-request-body-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-request-body-schema-properties-descriptions-info
    message: Schema Description
  - code: openapi-request-body-schema-properties-names-camel-case-error
    message: Request Body Schema Property Names Camel Case
  - code: openapi-request-body-schema-properties-type-info
    message: Request Body Schema Properties Format
  - code: openapi-request-body-schema-properties-descriptions-length-error
    message: Schema Description Length
  - code: openapi-response-put-400-status-code-warn
    message: 400 Status Code for PUT Responses
  - code: openapi-response-put-404-status-code-warn
    message: 404 Status Code for PUT Responses
  - code: openapi-response-put-500-status-code-error
    message: 500 Status Code for PUT Responses
  - code: openapi-response-put-204-status-code-info
    message: PUT 204 Status Code
  - code: openapi-response-put-204-no-body-error
    message: No Response Body PUT
  - code: openapi-no-request-body-on-delete-info
    message: DELETE Request Body
  - code: openapi-response-delete-400-status-code-warn
    message: 400 Status Code for DELETE Responses
  - code: openapi-response-delete-404-status-code-error
    message: 404 Status Code for DELETE Responses
  - code: openapi-response-delete-500-status-code-error
    message: 500 Status Code for DELETE Responses
  - code: openapi-response-delete-204-status-code-info
    message: DELETE 204 Status Code
  - code: openapi-operations-description-length-error
    message: Operation Description Length
  - code: openapi-request-body-on-post-info
    message: Request Body POST
  - code: openapi-request-body-content-on-post-info
    message: Request Body Content POST
  - code: openapi-request-body-json-media-type-on-post-info
    message: JSON Media Type POST
  - code: openapi-response-post-400-status-code-warn
    message: 400 Status Code for POST Responses
  - code: openapi-response-post-404-status-code-warn
    message: 404 Status Code for POST Responses
  - code: openapi-response-post-500-status-code-error
    message: 500 Status Code for POST Responses
  - code: openapi-response-post-201-status-code-info
    message: POST 201 Status Code
  - code: openapi-response-get-201-content-info
    message: POST Content
  - code: openapi-response-post-201-media-type-info
    message: JSON Media Type POST
  - code: openapi-response-post-201-media-type-schema-info
    message: Schema POST
  - code: openapi-response-post-201-schema-components-warn
    message: GET Response 201 Schema Components
  - code: openapi-response-post-201-schema-ref-error
    message: GET Response 201 Schema Ref
  - code: openapi-response-post-201-schema-ref-info
    message: GET Response 201 Schema Ref
  - code: openapi-security-schemes-error
    message: Security Scheme
  - code: openapi-schema-names-camel-case-warn
    message: Schema Name Camel Case
  - code: openapi-schema-names-snake-case-warn
    message: Schema Name Snake Case
  - code: openapi-schema-type-info
    message: Schema Type
  - code: openapi-schema-description-info
    message: Schemas has a description.
  - code: openapi-schema-properties-format-error
    message: Schema Properties Format
  - code: openapi-schema-properties-names-pascal-case-error
    message: Schema Property Names Pascal Case
  - code: openapi-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-schema-properties-descriptions-info
    message: Schema Description
  - code: openapi-schema-properties-pii-info
    message: Schema PII
  - code: openapi-schema-properties-enum-info
    message: Schema Property Enum
  - code: openapi-schema-properties-enum-casing-error
    message: Schema Property Enum Casing
  - code: openapi-schema-properties-nullable-error
    message: Schema Properties Format
  - code: openapi-schema-properties-type-info
    message: Schema Properties Format
  - code: openapi-schema-properties-names-camel-case-error
    message: Schema Property Names Camel Case
  - code: openapi-schema-properties-nullable-info
    message: Schema Properties Nullable
  - code: openapi-schema-properties-type-error
    message: Schema Properties Type
  - code: openapi-schema-properties-allof-info
    message: Schema Properties AllOf
  - code: invalid-ref
    message: '''#/components/schemas/File'' does not exist'
  - code: openapi-schema-properties-names-length-error
    message: Schema Properties Name Length
