info:
  title: Twilio - Insights
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Voice/Settings:
    description: 'TODO: Resource-level docs'
    get:
      description: Get the Voice Insights Settings.
      tags:
        - InsightsV1Setting
    post:
      description: Update a specific Voice Insights Setting.
      tags:
        - InsightsV1Setting
  /v1/Voice/{CallSid}/Annotation:
    description: 'TODO: Resource-level docs'
    post:
      description: Update an Annotation for a specific Call.
      tags:
        - InsightsV1Annotation
    get:
      description: Get the Annotation for a specific Call.
      tags:
        - InsightsV1Annotation
  /v1/Voice/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - InsightsV1Call
  /v1/Voice/Summaries:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Summaries.
      tags:
        - InsightsV1CallSummaries
  /v1/Conferences/{ConferenceSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Conference Summary.
      tags:
        - InsightsV1Conference
  /v1/Conferences:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Conference Summaries.
      tags:
        - InsightsV1Conference
  /v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Conference Participant Summary for a Conference.
      tags:
        - InsightsV1ConferenceParticipant
  /v1/Conferences/{ConferenceSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Conference Participants Summaries for a Conference.
      tags:
        - InsightsV1ConferenceParticipant
  /v1/Voice/{CallSid}/Events:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Insight Events for a Call.
      tags:
        - InsightsV1Event
  /v1/Voice/{CallSid}/Metrics:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Call Metrics for a Call.
      tags:
        - InsightsV1Metric
  /v1/Voice/{CallSid}/Summary:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a specific Call Summary.
      tags:
        - InsightsV1CallSummary
  /v1/Video/Rooms/{RoomSid}/Participants/{ParticipantSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get Video Log Analyzer data for a Room Participant.
      tags:
        - InsightsV1Participant
  /v1/Video/Rooms/{RoomSid}/Participants:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of room participants.
      tags:
        - InsightsV1Participant
  /v1/Video/Rooms/{RoomSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Get Video Log Analyzer data for a Room.
      tags:
        - InsightsV1Room
  /v1/Video/Rooms:
    description: 'TODO: Resource-level docs'
    get:
      description: Get a list of Programmable Video Rooms.
      tags:
        - InsightsV1Room
tags:
  - name: InsightsV1Annotation
  - name: InsightsV1Call
  - name: InsightsV1CallSummaries
  - name: InsightsV1CallSummary
  - name: InsightsV1Conference
  - name: InsightsV1ConferenceParticipant
  - name: InsightsV1Event
  - name: InsightsV1Metric
  - name: InsightsV1Participant
  - name: InsightsV1Room
  - name: InsightsV1Setting
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio.com/help/
