info:
  title: Twilio - Media
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/MediaProcessors:
    description: >-
      A MediaProcessor resource provides the ability to capture content from a
      web application with a Twilio Media Extension to create a livestream.
    post:
      description: ''
      tags:
        - Media
        - Processors
    get:
      description: Returns a list of MediaProcessors.
      tags:
        - Media
        - Processors
  /v1/MediaProcessors/{Sid}:
    description: >-
      A MediaProcessor resource provides the ability to capture content from a
      web application with a Twilio Media Extension to create a livestream.
    get:
      description: Returns a single MediaProcessor resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
    post:
      description: Updates a MediaProcessor resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
  /v1/MediaRecordings/{Sid}:
    description: >-
      A MediaRecording resource exposes recording metadata and allows the
      deletion of a particular recording.
    delete:
      description: Deletes a MediaRecording resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
    get:
      description: Returns a single MediaRecording resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
  /v1/MediaRecordings:
    description: >-
      A MediaRecording resource exposes recording metadata and allows the
      deletion of a particular recording.
    get:
      description: Returns a list of MediaRecordings.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
  /v1/PlayerStreamers/{Sid}:
    description: >-
      A PlayerStreamer resource provides the ability to send a livestream to a
      JavaScript, iOS, or Android Player SDK.
    get:
      description: Returns a single PlayerStreamer resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
    post:
      description: Updates a PlayerStreamer resource identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
  /v1/PlayerStreamers:
    description: >-
      A PlayerStreamer resource provides the ability to send a livestream to a
      JavaScript, iOS, or Android Player SDK.
    post:
      description: ''
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
    get:
      description: Returns a list of PlayerStreamers.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
  /v1/PlayerStreamers/{Sid}/PlaybackGrant:
    description: >-
      A PlaybackGrant resource allows developers to generate a grant to
      initialize the Twilio Live Player SDK and connect to a livestream.
    post:
      description: ''
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
        - Playback
        - Grant
    get:
      description: >-
        **This method is not enabled.** Returns a single PlaybackGrant resource
        identified by a SID.
      tags:
        - Media
        - Processors
        - Sid
        - Recordings
        - Player
        - Streamers
        - Playback
        - Grant
tags:
  - name: MediaV1MediaProcessor
  - name: MediaV1MediaRecording
  - name: MediaV1PlaybackGrant
  - name: MediaV1PlayerStreamer
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
