info:
  title: Twilio - Monitor
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Alerts/{Sid}:
    description: Debugger alerts
    get:
      description: ''
      tags:
        - MonitorV1Alert
  /v1/Alerts:
    description: Debugger alerts
    get:
      description: ''
      tags:
        - MonitorV1Alert
  /v1/Events/{Sid}:
    description: Debugger events
    get:
      description: ''
      tags:
        - MonitorV1Event
  /v1/Events:
    description: Debugger events
    get:
      description: Returns a list of events in the account, sorted by event-date.
      tags:
        - MonitorV1Event
tags:
  - name: MonitorV1Alert
  - name: MonitorV1Event
x-maturity:
  - name: GA
    description: This product is Generally Av
