info:
  title: Twilio - Pricing
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Trunking/Countries:
    description: Trunking pricing by country
    get:
      description: ''
      tags:
        - PricingV2Country
  /v2/Trunking/Countries/{IsoCountry}:
    description: Trunking pricing by country
    get:
      description: Fetch a specific Country.
      tags:
        - PricingV2Country
  /v2/Trunking/Numbers/{DestinationNumber}:
    description: Trunking pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      tags:
        - PricingV2Number
  /v2/Trunking/Numbers:
    description: Trunking pricing for a specific phone number
  /v2/Voice:
    description: Voice pricing
  /v2/Voice/Countries:
    description: Voice pricing by country
    get:
      description: ''
      tags:
        - PricingV2Country
  /v2/Voice/Countries/{IsoCountry}:
    description: Voice pricing by country
    get:
      description: Fetch a specific Country.
      tags:
        - PricingV2Country
  /v2/Voice/Numbers/{DestinationNumber}:
    description: Voice pricing for a specific phone number
    get:
      description: >-
        Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      tags:
        - PricingV2Number
  /v2/Voice/Numbers:
    description: Voice pricing for a specific phone number
tags:
  - name: PricingV2Country
  - name: PricingV2Number
x-maturity:
  - name: GA
    description: This product is Generally Av
