openapi: 3.0.3
info:
  title: Analytics Datastore API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  url: https://developer.factset.com/api-catalog/analytics-datastore-api
  description: API Documentation
tags:
  - name: Mappings
    description: >-
      Retrieves a mapping with a Location header to redirect to the underlying
      data
  - name: Objects
    description: Retrieves Objects and their underlying data
  - name: Documents
    description: Retrieves Document metadata and URL locations to underlying data
paths:
  /analytics/pub-datastore/swivel/v1/{document}/{accountId}/{date}:
    get:
      tags:
        - Mappings
      summary: Redirects to the raw PPT/PDF output created by the Publisher service.
      description: "Takes report parameter inputs and returns the object location for the specified report via a 302 redirect.\r\n\r\nNote: Due to Swagger UI functionality, the redirect is automatically followed when using 'Try it out', so instead of the 302 Header response, a 200 is returned with the Cargo response Body."
  /analytics/pub-datastore/swivel/v1/{document}/{assetName}/{reportId}/{tileId}/{accountId}:
    get:
      tags:
        - Mappings
      summary: >-
        Redirects to the underlying PA/SPAR data represented in a Stach format,
        with no as of date specified.
      description: "Takes report parameter inputs and returns the object location for the specified report via a 302 redirect.\r\n\r\nNote: Due to Swagger UI functionality, the redirect is automatically followed when using 'Try it out', so instead of the 302 Header response, a 200 is returned with the Cargo response Body."
  /analytics/pub-datastore/swivel/v1/{document}/{assetName}/{reportId}/{tileId}/{accountId}/{date}:
    get:
      tags:
        - Mappings
      summary: Redirects to the underlying PA/SPAR data represented in a Stach format.
      description: "Takes report parameter inputs and returns the object location for the specified report via a 302 redirect.\r\n\r\nNote: Due to Swagger UI functionality, the redirect is automatically followed when using 'Try it out', so instead of the 302 Header response, a 200 is returned with the Cargo response Body."
  /analytics/pub-datastore/swivel/v1/{document}/{assetName}/{reportId}/{tileId}/{accountId}/{configId}/{date}:
    get:
      tags:
        - Mappings
      summary: Redirects to the underlying Insight/Vault data in a Stach format.
      description: "The inclusion of a configId in the path indicates this is for Insight/Vault mappings only, as PA/SPAR mappings do not support the concept of configuration id.\r\n\r\nTakes report parameter inputs and returns the object location for the specified report via a 302 redirect.\r\n\r\nNote: Due to Swagger UI functionality, the redirect is automatically followed when using 'Try it out', so instead of the 302 Header response, a 200 is returned with the Cargo response Body."
  /analytics/pub-datastore/cargo/v1/groups/{groupId}/objects/{objectId}:
    get:
      tags:
        - Objects
      summary: >-
        Gets an object given an ID. In this case ID retrieved from mapping
        Location header, object data in response body.
      description: "Raw object data can be found in the response body. This can be either the mapped PDF/PPT or STACH json, depending on the mapping. https://pages.github.factset.com/analytics-reporting/stachschema/#/ \r\n\nOptional request header \"accept-encoding\", with allowed values of \"br\" and \"gzip\". If accept-encoding is passed, the response is compressed."
  /analytics/pub-datastore/tag-search/v1/documents/search:
    post:
      tags:
        - Documents
      summary: Gets a list of Documents that a user has access to.
      description: "Retrieves metadata around documents stored in the Analytics Datastore Service. Each Document will have a 'url' property which will act as a re-direct to the underlying document data\r\n\r\nThis end point supports pagination and filtering through the use of the request body listed below.\r\n\r\nTo discover what tags are available to filter on, see GET /tags and GET /tags/{name}/values to retrieve these filter values.\r\n\r\nSimilarly, to discover what product types are available to filter on, see POST /product-types/search to retrieve a list of product types."
  /analytics/pub-datastore/tag-search/v1/tags:
    get:
      tags:
        - Documents
      summary: Gets a list of tag definitions for the user.
      description: >-
        Tag definitions consist of a name and a type. Use this end point to see
        a list of pre-existing tags that can be used to filter on the Documents
        end point.
  /analytics/pub-datastore/tag-search/v1/tags/{name}:
    get:
      tags:
        - Documents
      summary: Get a single tag definition based on its name
      description: Retrieve a tag definition based on its name
  /analytics/pub-datastore/tag-search/v1/tags/{name}/values:
    post:
      tags:
        - Documents
      summary: Gets a list of tag values for the given name
      description: >-
        Returns a list of tag values depending on the name provided. Supports
        filtering on additional tag name value pairs, which operates as an 'AND'
        where the Document must have the tag name specified in the path AND the
        filtered parameter.
  /analytics/pub-datastore/tag-search/v1/product-types/search:
    post:
      tags:
        - Documents
      summary: Gets a list of product types that a user has access to.
      description: >-
        Retrieves a list of product types that have been specified across all
        documents the user has access to
