weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation ID Camel Case
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-length-error
    message: Operation Summary Length
  - code: openapi-operations-summary-period-none-error
    message: Operation Summary Period
  - code: openapi-parameters-schema-error
    message: Parameter Schema Type
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-required-error
    message: Parameters MUST have a required property.
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-query-names-camel-case-error
    message: Parameter Query Name Camel Case
  - code: openapi-parameters-query-names-snake-case-error
    message: Parameter Query Name Snake Case
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-response-get-400-status-code-warn
    message: 400 Status Code for GET Responses
  - code: openapi-response-get-404-status-code-warn
    message: 404 Status Code for GET Responses
  - code: openapi-response-get-500-status-code-error
    message: 500 Status Code for GET Responses
  - code: openapi-response-get-200-content-error
    message: GET Content
  - code: openapi-response-get-200-status-code-info
    message: GET Response Has 200 Status Code
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-operations-description-length-error
    message: Operation Description Length
  - code: openapi-parameters-enum-info
    message: Parameter Enum
  - code: openapi-parameters-enum-casing-info
    message: Parameter Enum Upper Snake Case
  - code: openapi-parameters-enum-casing-error
    message: Parameter Enum Upper Snake Case
  - code: openapi-info-contact-error
    message: Contact Object
  - code: openapi-info-description-error
    message: Info Description
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-name-info
    message: Tag Name
  - code: openapi-tags-description-info
    message: Tag Descriptions
