openapi: 3.0.0
info:
  title: FactSet GeoRev API
tags:
  - name: Regions
    description: >-
      Get the Super-Regions, Regions, and Area Revenue breakdowns for a
      requested list of symbols.
  - name: Countries
    description: Get the Country Revenue breakdown for all countries
paths:
  /factset-georev/v1/regions:
    get:
      tags:
        - Regions
      summary: Gets the revenue details for the requested Regions
      description: >
        Gets the Geographic Revenue, Percents, Confidence, and Ranks for a
        requested list of ids and Regions, for a given start-date and end-date.
        Regions represent a taxonomy of Super Regions, Regions, and Areas, with
        Super Regions being the largest collection. *Country specific revenue
        can be requested in the /countries endpoint.*
    post:
      tags:
        - Regions
      summary: >-
        Gets the revenue details for the requested Regions. Use for large lists
        of company ids.
      description: >
        Gets the Geographic Revenue, Percents, Confidence, and Ranks for a
        requested list of ids and Regions, for a given start-date and end-date.
        Regions represent a taxonomy of Super Regions, Regions, and Areas, with
        Super Regions being the largest collection. *Country specific revenue
        can be requested in the /countries endpoint.*
  /factset-georev/v1/countries:
    get:
      tags:
        - Countries
      summary: Gets the revenue details for the requested Countries.
      description: >
        Gets the **Countries'** Geographic Revenue, Percents, Confidence, and
        Ranks for a requested list of ids and country ISO codes, for a given
        start-date and end-date. 300 countries are supported. Countries
        represent the fourth and bottom level of the GeoRev taxonomy. Visit [OA
        8754](https://my.apps.factset.com/oa/pages/8754) for a list of ISO2
        Country Codes. By default, the service will return all Countries for the
        requested security.
    post:
      tags:
        - Countries
      summary: >-
        Gets the revenue details for the requested Countries. Use for large
        lists of ids.
      description: >
        Gets the **Countries'** Geographic Revenue, Percents, Confidence, and
        Ranks for a requested list of ids and country ISO codes, for a given
        start-date and end-date. Nearly 300 countries are supported. Countries
        represent the fourth and bottom level of the GeoRev taxonomy. The full
        list of countries and their related regional mappings can be found by
        using the /country-mappings endpoint or visit [OA
        8754](https://my.apps.factset.com/oa/pages/8754) for a list of ISO2 Coun
