openapi: 3.0.0
info:
  title: FactSet Options API
tags:
  - name: Option Chains & Screening
    description: >-
      Generate a list or universe of options ids based on underlying securities
      or other conditions
  - name: Snapshot
    description: A generic profile for a list of option securities as of a specific date
  - name: Reference
    description: Option Reference Information and Dates
  - name: Prices & Volume
    description: >-
      Option Prices & Volume information for a requested time-range for the
      option security or aggregated for all options associated to the underlying
      security
  - name: Risk Measures
    description: Option Risk measures such as Greeks, Implied Volatilities, and Calculators
paths:
  /factset-options/v1/chains:
    post:
      tags:
        - Option Chains & Screening
      summary: >-
        Returns all the underlying option identifiers for the specified
        underlying Security identifier
      description: >
        Returns all the underlying option identifiers for the underlying
        security identifier. Specify the date and or exhcange for the list of
        options associated to the id. 

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/option-screening:
    post:
      tags:
        - Option Chains & Screening
      summary: >-
        Returns all the option identifiers based on the conditions provided as
        input in the request
      description: >
        Returns all the option identifiers based on the conditions provided as
        input in the request. Conditions are as follows and will follow "AND"
        logic if more than one condition is applied and allows up to **three
        conditions** using AND Logic.If a condition is used the accompanying
        value MUST be used - 

        |conditions|description|

        |||

        |P_OPT_UNDERLYING_SECURITY_E|Underlying Security Equal To|

        |P_OPT_STRIKE_PRICE_E|Strike Price Equal To|

        |P_OPT_EXP_DATEN_E|Expiration Date (YYYYMMDD) Equal To|

        |P_OPT_VOLUME_G|Volume Greater Than|

        |P_OPT_VOLUME_GE|Volume Greater Than or Equal To|

        |P_OPT_VOLUME_L|Volume Less Than|

        |P_OPT_VOLUME_LE|Volume Less Than or Equal To|

        |P_OPT_VOLUME_E|Volume Equal To|

        |P_OPT_OPTION_TYPE_E|Option Type (1= Equity, 2=Index)|

        |P_OPT_CALL_OR_PUT_E|Call or Put (0=Call, 1=Put)|

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/snapshot:
    post:
      tags:
        - Snapshot
      summary: >-
        Returns all the profile information for the list of identifiers as of a
        specific date
      description: >
        Returns all the profile information for the list of identifiers for a
        specific date. The data includes - 

        * Expiration Date

        * Greek - Delta

        * Implied Volatility

        * Price 

        * Style

        * Type

        * Underlying Security

        * Underlying Security Price

        * Open Interest

        * Name

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/references:
    post:
      tags:
        - Reference
      summary: >-
        Returns basic reference details for the options such as currency,
        exchange, symbols, flags and more
      description: >
        Returns basic reference details for the options. Data items include - 

        * Name

        * Exchange

        * Call or Put Flag

        * Call or Put Pair Symbol

        * Other symbols such as OPRA17 and OCC21

        * Currency

        * Underlying Security Symbols

        * Expiration Month, Dates, and Frequency


        *For details or definitions of all available response fields visit the
        associated schema.*

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/dates:
    post:
      tags:
        - Reference
      summary: Returns option security dates such as expiration and trade.
      description: >
        Returns all relevant dates such as  for the specified Option identifier.
        Data Items include - 

        * Expiration Date

        * First Dates for Ask, Bid, Settlement, and Trade

        * Last Dates for Ask, Bid, Settlement, and Trade

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/prices:
    post:
      tags:
        - Prices & Volume
      summary: >-
        Returns the pricing related information for the specified option
        identifier
      description: >
        Returns the pricing related information for the specified option
        identifier. Items include - 

        * Ask

        * Bid

        * Mid

        * Mid Bid Ask

        * Settlement

        * Last Price Type (Settlement or MidBidAsk)

        * Last Price

        * Strike Price

        * Underlying Security Price

        * 52 Week High/Low

        * Open, High, Low for day. Note securities must be trading for day
        requested.

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/underlying-volume:
    post:
      tags:
        - Prices & Volume
      summary: >-
        Returns the aggregate volume and open interest for the list of the
        options under the specified security identifier
      description: >
        Return the Volume and Open Interest details for list of the options for
        the specified underlying security identifier. The data is aggregated for
        all options contracts associated to the underlying id, or specified in
        the request only the contracts listed on a specific exchange. Data
        Includes - 

        * Put Call Ratio 

        * Total Put Volume & Open Interest

        * Total Call Volume & Open Interest

        * Total Put & Call Volume & Open Interest

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/volume:
    post:
      tags:
        - Prices & Volume
      summary: Returns the volume details for the specified option identifier
      description: >
        Returns the volume details for the specified option identifier for a
        specified exchange. Data items include - 

        * Open Interest

        * Volume

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/greeks:
    post:
      tags:
        - Risk Measures
      summary: Returns all the Greeks details for the specified option identifier
      description: >
        Returns all the greeks details for the specified option identifier.
        Greeks provide quantifiable factors for measuring the option's price
        sensativity. Greeks include -


        |Greek|Description|

        ||---|

        |Delta| The ratio comparing the change in the price of the underlying
        asset to the corresponding change in the price of a derivative.
        Sometimes referred to as the "hedge ratio". For example, with respect to
        call options, a delta of 0.7 means that for every $1 the underlying
        stock increases, the call option will increase by $0.70. Put option
        deltas, on the other hand, will be negative, because as the underlying
        security increases, the value of the option will decrease. So a put
        option with a delta of -0.7 will decrease by $0.70 for every $1 the
        underlying increases in price. As an in-the-money call option nears
        expiration, it will approach a delta of 1.00, and as an in-the-money put
        option nears expiration, it will approach a delta of -1.00.|

        |Gamma| The rate of change for delta with respect to the underlying
        asset's price. Mathematically, gamma is the first derivative of delta
        and is used when trying to gauge the price of an option relative to the
        amount it is in or out of the money. When the option being measured is
        deep in or out of the money, gamma is small. When the option is near the
        money, gamma is largest.|

        |Rho|The rate at which the price of a derivative changes relative to a
        change in the risk-free rate of interest. Rho measures the sensitivity
        of an option or options portfolio to a change in interest rate.|

        |Theta|A measure of the rate of decline in the value of an option due to
        the passage of time. Theta can also be referred to as the time decay on
        the value of an option. If everything is held constant, then the option
        will lose value as time moves closer to the maturity of the option. For
        example, if the strike price of an option is $1,150 and theta is 53.80,
        then in theory the value of the option will drop $53.80 per day. The
        measure of theta quantifies the risk that time imposes on options as
        options are only exercisable for a certain period of time.|

        |Vega|The amount that the price of an option changes compared to a 1%
        change in volatility. Vega changes when there are large price movements
        in the underlying asset and vega falls as the option gets closer to
        maturity. Vega can change even if there is no change in the price of the
        underlying asset, this would happen if there is a change in expected
        volatility. For example, if the vega of an option is -96.94 and if
        implied volatility were to rise by 1% then the option value would fall
        by $96.94.|


        Note
          * Each step in the binomial model represents a change in time, therefore, point estimates of the Greeks can be calculated for American options. The following can be used to calculate the Greeks for the Binomial Option Pricing Model (BOPM) pricing model, using the notation fstep,node so f1,1 represents the option price at the first step, top node (nodes are counted at each step starting with 0 at the bottom. See [Constructing the Tree](https://my.apps.factset.com/oa/pages/17735#tree) for more information).
          
        For more detials on calculation methodologies, visit [OA
        14933](https://my.apps.factset.com/oa/pages/14933). 

          *Currently only OPRA Exchange is supported with exchange ISO "USA"*
  /factset-options/v1/implied-volatility:
    post:
      tags:
        - Risk Measures
      summary: >-
        Returns the implied volatility information for the specified option
        identifier
      description: >
        Returns the Implied Volatility for the specified option across European
        and American contracts. For more details regarding Implied Volatility
        calculations visit - [OA
        14932](https://my.apps.factset.com/oa/pages/14932)


        *Currently the following exchanges are not supported for API use cases -
        CME, CMEE, CBT, CBTE, NYM, NYME*
  /factset-options/v1/atm-implied-volatility:
    post:
      tags:
        - Risk Measures
      summary: >-
        Returns the at-the-money (ATM) implied volatility details for the
        specified underlying security identifier
      description: >
        Returns weighted average of the implied volatilities from the options
        listed for a specified security identifier. 


        There are three different methods available for calculating at-the-money
        implied volatility (ATM IV), which gives a weighted average of the
        implied volatilities from the options listed on a given stock. They are
        ATM IV (Filtered), ATM IV (Filtered with Smoothing), and ATM IV
        (Market). Each of these ATM IV calculations is available for just the
        calls on a given stock, just the puts, or the composite of both the
        calls and puts.

        This at-the-money implied volatility market can calculated for different
        periods -

        * One Month

        * Two Months

        * Three Months

        * Four Months

        * Five Months

        * Six Months


        *For more details regarding ATM Volatility calculations, visit [OA
        16276](https://my.apps.factset.com/oa/pages/16276)*

          *Currently only OPRA Exchange traded options are 
