openapi: 3.0.0
info:
  title: FactSet Ownership API
paths:
  /factset-ownership/v1/fund-holdings:
    get:
      tags:
        - Fund Holdings
      summary: Get underlying holdings information for a requested fund identifer.
      description: >
        Gets holdings information for list of fund identifiers. The service
        allows you to filter by the TopN holdings and Asset Type.
    post:
      tags:
        - Fund Holdings
      summary: Get holdings for a list of funds.
      description: Gets Holding information for a long list of Fund objects.
  /factset-ownership/v1/security-holders:
    get:
      tags:
        - Security Holders
      summary: Get security ownership data for requested security identifers.
      description: >
        Gets security ownership details and activity for the requested security
        identifiers. The services allows filtering by "Topn" holders and by
        holder "type", such as Institutions, Insiders, and Stakeholders.
    post:
      tags:
        - Security Holders
      summary: Get security ownership data for a list of requested securities.
      description: >
        Gets security ownership details and activity for the requested security
        identifiers. The services allows filtering by "Topn" holders and by
        holder "type", such as Institutions, Insiders, and Sta
