openapi: 3.0.3
info:
  title: FactSet Ownership API
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: Ownership
paths:
  /holders:
    get:
      tags:
        - Ownership
      summary: Holders of a company or fund
      description: Holders of a company or fund
