openapi: 3.0.0
info:
  title: Portfolio Reporting Batcher
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/portfolio-reporting-batcher-api
paths:
  /jobs/{type}/{name}:
    parameters:
      - null
      - null
    get:
      summary: Get details for the given PRB job
      tags:
        - Jobs
      description: >-
        Use this endpoint to fetch the documents, tasks, accounts, and/or runs
        for the PRB job given in the path. Please note jobs with type PD will
        not return tasks nor accounts so this will be ignored if given as part
        of the array of attributes in the request.
  /runs:
    post:
      summary: trigger PRB jobs
      description: Use this endpoint with with POST method to trigger PRB jobs.
      tags:
        - Runs
  /runs/{id}/status:
    get:
      summary: check the status for a particular run ID
      tags:
        - Runs
      description: >-
        Use this endpoint to check the status of a run using the id from the
        POST /runs endpoint
    parameters:
      - null
tags:
  - name: Jobs
    description: These endpoints relate to PRB jobs
  - name: Runs
    description: These endpoints refer to specific runs for
