openapi: 3.0.0
info:
  title: Tick History
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/factset-tick-history-api
paths:
  /level1/coverage:
    get:
      tags:
        - Level 1
      summary: >-
        Returns the coverage for the requested ticker/isin along with other
        response fields for Level1 data.
      description: Returns coverage for specified tickers for Level1 Data
  /level1/files/create:
    post:
      tags:
        - Level 1
      summary: Requests the creation of tick-by-tick file
      description: Data available from 20120101 to previous day.
  /level1/files/status:
    get:
      tags:
        - Level 1
      summary: Returns the status of the ID
      description: Need to plug-in the id get from /create endpoint into /status endpoint
  /level1/files/get:
    get:
      tags:
        - Level 1
      summary: Returns the tick-by-tick data in files requested in the /create endpoint
      description: Returns the files from tickhistory endpoint
  /level1/files/minute-bars/create:
    post:
      tags:
        - Level 1
      summary: Requests the creation of Minute bars file
      description: >-
        1-minute bars available from 20120101 to previous day. Per request able
        to fetch upto 6 months of data.
  /level1/files/minute-bars/status:
    get:
      tags:
        - Level 1
      summary: Returns the status of the ID
      description: Need to plug-in the id get from /create endpoint into /status endpoint
  /level1/files/minute-bars/get:
    get:
      tags:
        - Level 1
      summary: Returns the Minute bars data in files requested in the /create endpoint
      description: Returns the files from tickhistory endpoint
  /level2/files/create:
    post:
      tags:
        - Level 2
      summary: Returns the ID for the requested data.
      description: Data available from past 6 years to previous day.
  /level2/files/status:
    get:
      tags:
        - Level 2
      summary: Returns the status of the ID
      description: Need to plug-in the id get from /create endpoint into /status endpoint
  /level2/files/get:
    get:
      tags:
        - Level 2
      summary: Returns the tick history files requested in the /create endpoint
      description: Returns the files from tickhistory endpoint
tags:
  - name: Level 1
    description: >-
      API provides access to check coverage and retrieve Level 1 historical tick
      data
  - name: Level 2
    description: API provides access to the  historical tick data up to 10 levels of depth
