openapi: 3.0.0
info:
  title: Classifications API
tags:
  - name: GICS
    description: >-
      Global Industry Classification Standard (GICS) Sectors, Industry Groups,
      Industries, and Sub-Industries.
paths:
  /classifications/v1/gics:
    get:
      tags:
        - GICS
      summary: Gets the GICS Direct Classifications
      description: >
        Gets the **Global Industry Classification Standard ("GICS")** Sectors,
        Industry Group, Industry, and Sub-Industry Names and Numbers for a
        requested list of ids and date range. All economic sectors have a
        two-digit identification code, all industry groups have a four-digit
        identification code, all industries have a six-digit identification
        code, and all sub-industries have an eight-digit identification code. To
        access the complete GICS structure and definitions, visit the [MSCI
        GICS](https://www.msci.com/gics) or [S&P
        GICS](https://www.spglobal.com/spdji/en/landing/topic/gics/) home pages.
        Coverage includes over 37,000 securities.

        *Licensing for GICS Classifications, Regions, and History is required in
        addition to FactSet API license. Reach out to your FactSet Account Team
        for assistance.*
    post:
      tags:
        - GICS
      summary: Returns the GICS classifications for the requested 'ids' and date range.
      description: >
        Gets the **Global Industry Classification Standard ("GICS")** Sectors,
        Industry Group, Industry, and Sub-Industry Names and Numbers for a
        requested list of ids and date range. All economic sectors have a
        two-digit identification code, all industry groups have a four-digit
        identification code, all industries have a six-digit identification
        code, and all sub-industries have an eight-digit identification code. To
        access the complete GICS structure and definitions, visit the [MSCI
        GICS](https://www.msci.com/gics) or [S&P
        GICS](https://www.spglobal.com/spdji/en/landing/topic/gics/) home pages.
        Coverage includes over 37,000 securities.

        *Licensing for GICS Classifications, Regions, and History is required in
        addition to FactSet API license. Reach out to your FactSet Account Team
        for as
