openapi: 3.0.3
info:
  title: FactSet Entity Report Builder
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: Entity Structure
paths:
  /structure:
    get:
      tags:
        - Entity Structure
      summary: Entity structure
      description: Returns full entity tree for table and tr
