openapi: 3.0.3
info:
  title: Open Risk API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: About
  - name: Operations
paths:
  /linear/{version}/riskmodels:
    get:
      summary: Get available risk models
      description: >-
        Get the list of available risk models, including their respective model
        codes required for use with other routes.
      tags:
        - About
  /linear/{version}/riskmodels/{modelCode}:
    get:
      summary: Get risk model details
      description: >-
        Get the meta data of the risk model for the corresponding modelCode.
        modelCode can be obtained via '/linear/{version}/riskmodels/' route.
      tags:
        - About
  /linear/{version}/stats:
    get:
      summary: Get available risk statistics details
      description: >-
        All base risk statistic names and their respective support and/or
        requirement for certain name-settings statistics options (such as:
        correlated specific risk, covariance isolation method, etc.), available
        levels, and security group calculation methodology. When
        'securityGroupMethod' is 'statSpecific', please refer to statistics
        documentation service for more information.
      tags:
        - About
  /linear/{version}/stats-names-only:
    get:
      summary: Get available risk statistics names
      description: >-
        All available risk statistic names including statistics names containing
        risk statistics options such as CSR (correlated specific risk)
      tags:
        - About
  /linear/{version}/health:
    get:
      summary: Get health of service
      description: Health status of the service
      tags:
        - About
  /linear/{version}/calculate/from-holdings:
    post:
      summary: Calculate risk statistics
      description: >-
        Calculate predicted risk statistics for provided holdings using risk
        model data. Asset symbols and market values/weights are required.
      tags:
        - Operations
  /linear/{version}/generate/id-mapping:
    post:
      summary: Generate risk model ID mapping
      description: >-
        Resolve all input holdings IDs against a risk model for coverage and
        provide a mapping to security indices in the model or the reason for
        exclusion
      tags:
        - Operations
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/op
