openapi: 3.0.0
info:
  title: FactSet Symbology API
paths:
  /symbology/v3/identifier-resolution:
    get:
      tags:
        - Identifier Resolution
      summary: >-
        Returns the specified output identifiers for the specified input
        identifier.
      description: >
        The Identifier Resolution endpoint provides flexibility for requesting
        and receiving both third-party and FactSet Permanent identifiers. Users
        can both input and output most of the listed identifiers, with
        exceptions noted below.  All input and output symbols must be declared,
        and users have the ability to resolve one input symbol to many different
        output symbols in one request. 

        * **BIC*** - Bank Identification Code (e.g. ABXXHKH1)

        * **CIK** - Edgar Central Index Keys (e.g. 0000100331)

        * **CRD** - Central Registration Depository (e.g. 149722)

        * **DUNS** - Dun & Bradstreet Data Universal Numbering System (e.g.
        687741991) (Input only)

        * **EIN** - Employer Identification Number (e.g. 953540776)

        * **FITCH*** - Fitch Ratings Identifier (e.g. 47504)

        * **LEI** - Legal Entity Identifier (e.g. 549300A6K7JX8EX2QZ33)

        * **MD*** - Moody's Ratings Identifier (e.g. 0823736553)

        * **SPR*** - S&P Ratings Identifier (e.g. 301939)

        * **VALOREN** - Valoren ("Valor") Identification (e.g. 685558) (Input
        only)

        * **WKN*** - German Securities Identification ("Wertpapierkennnummer")
        (e.g. A0MU9T)

        * **UKCH** - UK Company House Identifier (e.g.CE012494)

        * **RSSD** - Federal Reserve RSSD Identifier (1139297)

        * **SEDOL***

        * **CUSIP***

        * **fsymEntityId** - FactSet entity Id

        * **fsymSecurityId** - FactSet security level permanent identifier

        * **fsymRegionalId** - FactSet regional level permanent identifier

        * **fsymListingId** - FactSet listing level permanent identifier

        * **ISIN***

        * **tickerExchange** - Ticker Exchange is a marketplace where stocks,
        bonds, commodities, and derivatives are bought and sold. (e.g.
        GOOGL-NAS)

        * **tickerRegion** - Ticker Region is the geographical region or market
        segment where a particular stock or security is listed and traded. (e.g.
        GOOGL-US)

        * **bloombergFigi** - Bloomberg Listing/Regional/Security Identifier
        (output symbols: bloombergFigiListing, bloombergFigiRegional &
        bloombergFigiSecurity) (e.g. BBG009S39JY5)

        * **bloombergTicker** - Bloomberg Listing and Regional Ticker Identifier
        (output symbols: bloombergRegionalTicker & bloombergListingTicker) (e.g.
        GOOGL UW)

        * **GVKEY** - CompuStat Entity Identifier (e.g. 063172)(Input only)

        * **GVKEY & IID** - CompuStat Security Identifier (e.g.063172001) (Input
        only)

        * **JCN** - Japan Corporate Number (e.g. 9011101021173)

        * **LoanX** - Markit Bank Loan Security Identifier (e.g. LX130668)
        (Input only)

        * **MarkitRed** - Markit Entity Identifier (e.g. 3D337C) (Input only)


        **These symbol types require additional subscriptions. If you would like
        to gain access to these symbol types, please contact your FactSet
        Account Team or "Report Issue" above and our support teams can assist.*
    post:
      tags:
        - Identifier Resolution
      summary: Returns the specified output identifiers for the given input identifier.
      description: >
        The Identifier Resolution endpoint provides flexibility for requesting
        and receiving both third-party and FactSet Permanent identifiers. Users
        can both input and output most of the listed identifiers, with
        exceptions noted below.  All input and output symbols must be declared,
        and users have the ability to resolve one input symbol to many different
        output symbols in one request. 

        * **BIC*** - Bank Identification Code (e.g. ABXXHKH1)

        * **CIK** - Edgar Central Index Keys (e.g. 0000100331)

        * **CRD** - Central Registration Depository (e.g. 149722)

        * **DUNS** - Dun & Bradstreet Data Universal Numbering System (e.g.
        687741991) (Input only)

        * **EIN** - Employer Identification Number (e.g. 953540776)

        * **FITCH*** - Fitch Ratings Identifier (e.g. 47504)

        * **LEI** - Legal Entity Identifier (e.g. 549300A6K7JX8EX2QZ33)

        * **MD*** - Moody's Ratings Identifier (e.g. 0823736553)

        * **SPR*** - S&P Ratings Identifier (e.g. 301939)

        * **VALOREN** - Valoren ("Valor") Identification (e.g. 685558) (Input
        only)

        * **WKN*** - German Securities Identification ("Wertpapierkennnummer")
        (e.g. A0MU9T)

        * **UKCH** - UK Company House Identifier (e.g.CE012494)

        * **RSSD** - Federal Reserve RSSD Identifier (1139297)

        * **SEDOL***

        * **CUSIP***

        * **fsymEntityId** - FactSet entity Id

        * **fsymSecurityId** - FactSet security level permanent identifier

        * **fsymRegionalId** - FactSet regional level permanent identifier

        * **fsymListingId** - FactSet listing level permanent identifier

        * **ISIN***

        * **tickerExchange** - Ticker Exchange, a marketplace where stocks,
        bonds, commodities, and derivatives are bought and sold. (e.g.
        GOOGL-NAS)

        * **tickerRegion** - Ticker Region, geographical region or market
        segment where a particular stock or security is listed and traded. (e.g.
        GOOGL-US)

        * **bloombergFigi** - Bloomberg Listing/Regional/Security Identifier
        (output symbols: bloombergFigiListing, bloombergFigiRegional &
        bloombergFigiSecurity ) (e.g. BBG009S39JY5)

        * **bloombergTicker** - Bloomberg Listing and Regional Ticker Identifier
        (output symbols: bloombergRegionalTicker & bloombergListingTicker) (e.g.
        GOOGL UW)

        * **GVKEY** - CompuStat Entity Identifier (e.g. 063172)(Input only)

        * **GVKEY & IID** - CompuStat Security Identifier (e.g.063172001) (Input
        only)

        * **JCN** - Japan Corporate Number (e.g. 9011101021173)

        * **LoanX** - Markit Bank Loan Security Identifier (e.g. LX130668)
        (Input only)

        * **MarkitRed** - Markit Entity Identifier (e.g. 3D337C) (Input only)


        **These symbol types require additional subscriptions. If you would like
        to gain access to these symbol types, please contact your FactSet
        Account Team or "Report Issue" above and our support teams can assist.*
  /symbology/v3/historical-identifier-resolution:
    get:
      tags:
        - Historical Identifier Resolution
      summary: >-
        Returns the specified historical output identifiers for the given input
        identifier.
      description: >
        This endpoint enables the retrieval of historical CUSIP, SEDOL, ISIN,
        and tickerRegion identifiers. Users can input any of the listed
        identifiers and resolve one input symbol to multiple different output
        symbols in a single request. Both input and output symbols must be
        declared. The `asOfDate` field allows users to retrieve the full history
        of an identifier or the specific identifiers as of the requested date. 

        * **BIC*** - Bank Identification Code (e.g. ABXXHKH1) (Input only)

        * **CIK** - Edgar Central Index Keys (e.g. 0000100331) (Input only)

        * **CRD** - Central Registration Depository (e.g. 149722) (Input only)

        * **DUNS** - Dun & Bradstreet Data Universal Numbering System (e.g.
        687741991) (Input only)

        * **EIN** - Employer Identification Number (e.g. 953540776) (Input only)

        * **FITCH*** - Fitch Ratings Identifier (e.g. 47504) (Input only)

        * **LEI** - Legal Entity Identifier (e.g. 549300A6K7JX8EX2QZ33) (Input
        only)

        * **MD*** - Moody's Ratings Identifier (e.g. 0823736553) (Input only)

        * **SPR*** - S&P Ratings Identifier (e.g. 301939) (Input only)

        * **VALOREN** - Valoren ("Valor") Identification (e.g. 685558) (Input
        only)

        * **WKN*** - German Securities Identification ("Wertpapierkennnummer")
        (e.g. A0MU9T) (Input only)

        * **UKCH** - UK Company House Identifier (e.g.CE012494) (Input only)

        * **RSSD** - Federal Reserve RSSD Identifier (1139297) (Input only)

        * **SEDOL***

        * **CUSIP***

        * **fsymEntityId** - FactSet entity Id (Input only)

        * **fsymSecurityId** - FactSet security level permanent identifier
        (Input only)

        * **fsymRegionalId** - FactSet regional level permanent identifier
        (Input only)

        * **fsymListingId** - FactSet listing level permanent identifier (Input
        only)

        * **ISIN***

        * **tickerExchange** - Ticker Exchange is a marketplace where stocks,
        bonds, commodities, and derivatives are bought and sold. (e.g.
        GOOGL-NAS) (Input only)

        * **tickerRegion** - Ticker Region is the geographical region or market
        segment where a particular stock or security is listed and traded. (e.g.
        GOOGL-US)

        * **bloombergFigi** - Bloomberg Listing/Regional/Security Identifier
        (output symbols: bloombergFigiListing, bloombergFigiRegional &
        bloombergFigiSecurity ) (e.g. BBG009S39JY5) (Input only)

        * **bloombergTicker** - Bloomberg Listing and Regional Ticker Identifier
        (output symbols: bloombergRegionalTicker & bloombergListingTicker) (e.g.
        GOOGL UW) (Input only)

        * **GVKEY** - CompuStat Entity Identifier (e.g. 063172) (Input only)

        * **GVKEY & IID** - CompuStat Security Identifier (e.g.063172001) (Input
        only)

        * **JCN** - Japan Corporate Number (e.g. 9011101021173) (Input only)

        * **LoanX** - Markit Bank Loan Security Identifier (e.g. LX130668)
        (Input only)

        * **MarkitRed** - Markit Entity Identifier (e.g. 3D337C) (Input only) 


        **These symbol types require additional subscriptions. If you would like
        to gain access to these symbol types, please contact your FactSet
        Account Team or "Report Issue" above and our support teams can assist.*
    post:
      tags:
        - Historical Identifier Resolution
      summary: >-
        Returns the specified historical output identifiers for the given input
        identifier.
      description: >
        This endpoint enables the retrieval of historical CUSIP, SEDOL, ISIN,
        and tickerRegion identifiers. Users can input any of the listed
        identifiers and resolve one input symbol to multiple different output
        symbols in a single request. Both input and output symbols must be
        declared. The `asOfDate` field allows users to retrieve the full history
        of an identifier or the specific identifiers as of the requested date. 

        * **BIC*** - Bank Identification Code (e.g. ABXXHKH1) (Input only)

        * **CIK** - Edgar Central Index Keys (e.g. 0000100331) (Input only)

        * **CRD** - Central Registration Depository (e.g. 149722) (Input only)

        * **DUNS** - Dun & Bradstreet Data Universal Numbering System (e.g.
        687741991) (Input only)

        * **EIN** - Employer Identification Number (e.g. 953540776) (Input only)

        * **FITCH*** - Fitch Ratings Identifier (e.g. 47504) (Input only)

        * **LEI** - Legal Entity Identifier (e.g. 549300A6K7JX8EX2QZ33) (Input
        only)

        * **MD*** - Moody's Ratings Identifier (e.g. 0823736553) (Input only)

        * **SPR*** - S&P Ratings Identifier (e.g. 301939) (Input only)

        * **VALOREN** - Valoren ("Valor") Identification (e.g. 685558) (Input
        only)

        * **WKN*** - German Securities Identification ("Wertpapierkennnummer")
        (e.g. A0MU9T) (Input only)

        * **UKCH** - UK Company House Identifier (e.g.CE012494) (Input only)

        * **RSSD** - Federal Reserve RSSD Identifier (1139297) (Input only)

        * **SEDOL***

        * **CUSIP***

        * **fsymEntityId** - FactSet entity Id (Input only)

        * **fsymSecurityId** - FactSet security level permanent identifier
        (Input only)

        * **fsymRegionalId** - FactSet regional level permanent identifier
        (Input only)

        * **fsymListingId** - FactSet listing level permanent identifier (Input
        only)

        * **ISIN***

        * **tickerExchange** - Ticker Exchange, a marketplace where stocks,
        bonds, commodities, and derivatives are bought and sold. (e.g.
        GOOGL-NAS) (Input only)

        * **tickerRegion** - Ticker Region, geographical region or market
        segment where a particular stock or security is listed and traded. (e.g.
        GOOGL-US)

        * **bloombergFigi** - Bloomberg Listing/Regional/Security Identifier
        (output symbols: bloombergFigiListing, bloombergFigiRegional &
        bloombergFigiSecurity ) (e.g. BBG009S39JY5) (Input only)

        * **bloombergTicker** - Bloomberg Listing and Regional Ticker Identifier
        (output symbols: bloombergRegionalTicker & bloombergListingTicker) (e.g.
        GOOGL UW) (Input only)

        * **GVKEY** - CompuStat Entity Identifier (e.g. 063172) (Input only)

        * **GVKEY & IID** - CompuStat Security Identifier (e.g.063172001) (Input
        only)

        * **JCN** - Japan Corporate Number (e.g. 9011101021173) (Input only)

        * **LoanX** - Markit Bank Loan Security Identifier (e.g. LX130668)
        (Input only)

        * **MarkitRed** - Markit Entity Identifier (e.g. 3D337C) (Input only)


        **These symbol types require additional subscriptions. If you would like
        to gain access to these symbol types, please contact your FactSet
        Account Team or "Report Issue" above and our support teams can 
