info:
  title: Universal Screening API
openapi: 3.0.2
externalDocs:
  description: Read more about STACH 2.0's column organized schema
  url: https://factset.github.io/stachschema/#/v2/ColumnOrganized
paths:
  /v2/job/archive:
    post:
      description: Begins archive of screen to OFDB. Subject to rate limiting by serial.
      tags:
        - Screening Operations
  /v2/job/calculate:
    post:
      description: Begins calculation of screen. Subject to rate limiting by serial.
      tags:
        - Screening Operations
  /v2/job/{id}/status:
    get:
      description: Polls the job with a given screen ID and returns job status
      tags:
        - Screening Operations
  /v2/jobs:
    get:
      description: >-
        Retrieve list of all active job ids started by requester's
        username-serial
      tags:
        - Job Management
    delete:
      description: Delete all active jobs started by the requester's username-serial
      tags:
        - Job Management
  /v2/job/{id}:
    delete:
      description: Delete a specified job started by the requester's username-serial
      tags:
        - Job Management
    get:
      description: >-
        Retrieve results of complete screen calculation. Screens with more than
        10,000 rows will be returned in a paginated format. Results may be
        fetched in pages of 1,000 - 100,000 results with 10,000 being the
        default page size.
      tags:
        - Screening Operations
