openapi: 3.0.0
info:
  version: ''
  title: Payment Access Token
tags:
  - name: Tokens
paths:
  /payments/access_tokens:
    parameters:
      - null
    post:
      description: >-
        Use this endpoint to create a payment access token. A payment access
        token is required to process payments with the BigCommerce API.


        You can also generate a payment access token during checkout by using
        the `completeCheckout` mutation in the [GraphQL Storefront
        API](/docs/storefront/cart-checkout/guide/graphql-storefront#handling-payments).


        After the token is created, use the token to [Process a
        payment](/docs/rest-payments/processing#process-payment).


        **Required Fields**

        * order_id
      summary: Create Payment Access Token
      tags:
        - Create
        - Payment
        - Access
        - Token
        - Payments
        - Access_toke
