weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-openapi-version-301-info
    message: 3.0.1 Version of OpenAPI
  - code: openapi-openapi-version-310-info
    message: 3.1.0 Version of OpenAPI
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-description-length-error
    message: Info Description Length
  - code: openapi-info-terms-of-service-info
    message: Terms of Service
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-name-info
    message: Contact Name
  - code: openapi-info-contact-url-info
    message: Contact URL
  - code: openapi-info-contact-email-info
    message: Contact Email
  - code: openapi-info-license-info
    message: License Object
  - code: openapi-info-license-url-error
    message: Info License URL
  - code: openapi-info-license-name-error
    message: Info License Name
  - code: openapi-info-version-error
    message: Info Version
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-description-error
    message: Tag Descriptions
  - code: openapi-tags-name-info
    message: Tag Name
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-query-names-camel-case-error
    message: Parameter Query Name Camel Case
  - code: openapi-parameters-query-names-snake-case-error
    message: Parameter Query Name Snake Case
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-response-get-400-status-code-warn
    message: 400 Status Code for GET Responses
  - code: openapi-response-get-404-status-code-warn
    message: 404 Status Code for GET Responses
  - code: openapi-response-get-500-status-code-error
    message: 500 Status Code for GET Responses
  - code: openapi-response-get-200-status-code-info
    message: GET Response Has 200 Status Code
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-response-get-200-content-info
    message: GET Content
  - code: openapi-response-get-200-media-type-info
    message: JSON Media Type GET
  - code: openapi-response-get-200-media-type-schema-info
    message: Schema GET
  - code: openapi-response-get-200-schema-components-warn
    message: GET Response 200 Schema Components
  - code: openapi-response-get-200-schema-ref-warn
    message: GET Response 200 Schema Ref
  - code: openapi-schema-description-error
    message: Schema SHOULD have a description.
  - code: openapi-schema-names-camel-case-warn
    message: Schema Name Camel Case
  - code: openapi-schema-names-pascal-case-warn
    message: Schema Name Pascal Case
  - code: openapi-schema-names-snake-case-warn
    message: Schema Name Snake Case
  - code: openapi-schema-type-info
    message: Schema Type
  - code: openapi-schema-properties-format-error
    message: Schema Properties Format
  - code: openapi-schema-properties-names-pascal-case-error
    message: Schema Property Names Pascal Case
  - code: openapi-schema-properties-nullable-error
    message: Schema Properties Format
  - code: openapi-schema-properties-pii-info
    message: Schema PII
  - code: openapi-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-schema-properties-descriptions-info
    message: Schema Description
  - code: openapi-schema-properties-names-camel-case-error
    message: Schema Property Names Camel Case
  - code: openapi-security-schemes-info
    message: Security Scheme
